
TARGET_SPARK_SERVICES_SRC_PATH = $(SERVICES_MODULE_PATH)/src
NANOPB_SRC_PATH = $(SERVICES_MODULE_PATH)/nanopb

CPPSRC += $(call target_files,$(TARGET_SPARK_SERVICES_SRC_PATH),*.cpp)
CSRC += $(call target_files,$(TARGET_SPARK_SERVICES_SRC_PATH),*.c)

LOG_MODULE_CATEGORY = service
