#include "spark_wiring_diagnostics.h"

extern particle::SimpleUnsignedIntegerDiagnosticData g_rateLimitedEventsCounter;
extern particle::SimpleUnsignedIntegerDiagnosticData g_unacknowledgedMessageCounter;
extern particle::SimpleUnsignedIntegerDiagnosticData g_trasmittedMessageCounter;
extern particle::SimpleUnsignedIntegerDiagnosticData g_retransmittedMessageCounter;
extern particle::SimpleUnsignedIntegerDiagnosticData g_coapRoundTripMSec;
