#include "spark_wiring_diagnostics.h"

extern particle::SimpleIntegerDiagnosticData g_rateLimitedEventsCounter;
extern particle::SimpleIntegerDiagnosticData g_unacknowledgedMessageCounter;
extern particle::SimpleIntegerDiagnosticData g_trasmittedMessageCounter;
extern particle::SimpleIntegerDiagnosticData g_retransmittedMessageCounter;