#include "communication_diagnostic.h"

particle::SimpleIntegerDiagnosticData g_rateLimitedEventsCounter(DIAG_ID_CLOUD_RATE_LIMITED_EVENTS, DIAG_NAME_CLOUD_RATE_LIMITED_EVENTS);
particle::SimpleIntegerDiagnosticData g_unacknowledgedMessageCounter(DIAG_ID_CLOUD_UNACKNOWLEDGED_MESSAGES, DIAG_NAME_CLOUD_UNACKNOWLEDGED_MESSAGES);
particle::SimpleIntegerDiagnosticData g_trasmittedMessageCounter(DIAG_ID_CLOUD_TRANSMITTED_MESSAGES, DIAG_NAME_CLOUD_TRANSMITTED_MESSAGES);
particle::SimpleIntegerDiagnosticData g_retransmittedMessageCounter(DIAG_ID_CLOUD_RETRANSMITTED_MESSAGES, DIAG_NAME_CLOUD_RETRANSMITTED_MESSAGES);