#include "communication_diagnostic.h"

particle::SimpleUnsignedIntegerDiagnosticData g_rateLimitedEventsCounter(DIAG_ID_CLOUD_RATE_LIMITED_EVENTS, DIAG_NAME_CLOUD_RATE_LIMITED_EVENTS);
particle::SimpleUnsignedIntegerDiagnosticData g_unacknowledgedMessageCounter(DIAG_ID_CLOUD_UNACKNOWLEDGED_MESSAGES, DIAG_NAME_CLOUD_UNACKNOWLEDGED_MESSAGES);
particle::SimpleUnsignedIntegerDiagnosticData g_trasmittedMessageCounter(DIAG_ID_CLOUD_TRANSMITTED_MESSAGES, DIAG_NAME_CLOUD_TRANSMITTED_MESSAGES);
particle::SimpleUnsignedIntegerDiagnosticData g_retransmittedMessageCounter(DIAG_ID_CLOUD_RETRANSMITTED_MESSAGES, DIAG_NAME_CLOUD_RETRANSMITTED_MESSAGES);
particle::SimpleUnsignedIntegerDiagnosticData g_coapRoundTripMSec(DIAG_ID_CLOUD_COAP_ROUND_TRIP, DIAG_NAME_CLOUD_COAP_ROUND_TRIP);
