# Makefile that included by all modules - this defines the layout of the various modules

SHARED_MODULAR=$(PROJECT_ROOT)/modules/shared/nRF52840

MODULAR_FIRMWARE=y
# propagate to sub makes
MAKE_ARGS += MODULAR_FIRMWARE=y
USER_FIRMWARE_IMAGE_SIZE=0x20000
USER_FIRMWARE_IMAGE_LOCATION=0xD4000

# Ensure these defines are passed to all sub makefiles
GLOBAL_DEFINES += USER_FIRMWARE_IMAGE_SIZE=$(USER_FIRMWARE_IMAGE_SIZE)
GLOBAL_DEFINES += USER_FIRMWARE_IMAGE_LOCATION=$(USER_FIRMWARE_IMAGE_LOCATION)
GLOBAL_DEFINES += MODULAR_FIRMWARE=1

export PLATFORM_ID ?= 13

ifneq (,$(filter $(PLATFORM_ID),13 23))
ifeq ($(HYBRID_BUILD),y)
GLOBAL_DEFINES += LOG_COMPILE_TIME_LEVEL=LOG_LEVEL_NONE
endif
endif
