#pragma once

#include "dct_hal.h"

#define DCT_SERVER_PUBLIC_KEY_OFFSET 0
#define DCT_SERVER_PUBLIC_KEY_SIZE 384

#define DCT_SERVER_ADDRESS_OFFSET ((DCT_SERVER_PUBLIC_KEY_OFFSET) + (DCT_SERVER_PUBLIC_KEY_SIZE))
#define DCT_SERVER_ADDRESS_SIZE 128

#define DCT_ALT_SERVER_PUBLIC_KEY_OFFSET ((DCT_SERVER_ADDRESS_OFFSET) + (DCT_SERVER_ADDRESS_SIZE))
#define DCT_ALT_SERVER_PUBLIC_KEY_SIZE 192

#define DCT_ALT_SERVER_ADDRESS_OFFSET ((DCT_ALT_SERVER_PUBLIC_KEY_OFFSET) + (DCT_ALT_SERVER_PUBLIC_KEY_SIZE))
#define DCT_ALT_SERVER_ADDRESS_SIZE 128
