HAL_DYNALIB_MODULE_NAME = hal-dynalib
HAL_DYNALIB_MODULE_PATH ?= $(PROJECT_ROOT)/$(HAL_DYNALIB_MODULE_NAME)
include $(call rwildcard,$(HAL_DYNALIB_MODULE_PATH)/,include.mk)

HAL_DYNALIB_BUILD_PATH_EXT=$(BUILD_TARGET_PLATFORM)
HAL_DYNALIB_LIB_DIR = $(BUILD_PATH_BASE)/$(HAL_DYNALIB_MODULE_NAME)/$(HAL_DYNALIB_BUILD_PATH_EXT)
HAL_DYNALIB_LIB_DEP = $(HAL_DYNALIB_LIB_DIR)/lib$(HAL_DYNALIB_MODULE_NAME).a
