
MODULE=hal-dynalib
HAL_DYNALIB_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT = $(HAL_DYNALIB_BUILD_PATH_EXT)

DEPENDENCIES = hal services dynalib platform

include ../build/arm-tlm.mk

