/**
 * The dyanmic libraries exported by this module.
 */
PROVIDE ( dynalib_location_communication            = _system_part1_dynalib_table_flash_start + 0 );
PROVIDE ( dynalib_location_wifi_resource            = _system_part1_dynalib_table_flash_start + 4 );
PROVIDE ( dynalib_location_system_module_part1      = _system_part1_dynalib_table_flash_start + 8 );
PROVIDE ( dynalib_location_services                 = _system_part1_dynalib_table_flash_start + 12 );
PROVIDE ( dynalib_location_crypto                   = _system_part1_dynalib_table_flash_start + 16 );
