MODULE = proto_defs
PROTO_DEFS_MODULE_PATH = .

# Target this makefile is building.
TARGET_TYPE = a

BUILD_PATH_EXT = $(PROTO_DEFS_BUILD_PATH_EXT)

DEPENDENCIES = third_party/nanopb
MAKE_DEPENDENCIES = third_party/nanopb

include ../build/arm-tlm.mk
