ifeq ($(PLATFORM_ID),32)
COREMARK_DEPENDENCY = third_party/coremark

include $(PROJECT_ROOT)/$(COREMARK_DEPENDENCY)/import.mk

LIBS += $(notdir $(COREMARK_DEPENDENCY))
LIB_DIRS += $(COREMARK_LIB_DIR)

CFLAGS += -DENABLE_FQC_FUNCTIONALITY=1
CXXFLAGS += -DENABLE_FQC_FUNCTIONALITY=1
endif
