/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Fri Dec  1 00:45:35 2017. */

#ifndef PB_PARTICLE_CTRL_COMMON_PB_H_INCLUDED
#define PB_PARTICLE_CTRL_COMMON_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
