/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Dec  5 15:54:29 2017. */

#include "control.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif




/* @@protoc_insertion_point(eof) */
