/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Wed Nov 22 04:15:04 2017. */

#ifndef PB_PARTICLE_CTRL_CONTROL_PB_H_INCLUDED
#define PB_PARTICLE_CTRL_CONTROL_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _particle_ctrl_WiFiAntenna {
    particle_ctrl_WiFiAntenna_NONE = 0,
    particle_ctrl_WiFiAntenna_INTERNAL = 1,
    particle_ctrl_WiFiAntenna_EXTERNAL = 2,
    particle_ctrl_WiFiAntenna_AUTO = 3
} particle_ctrl_WiFiAntenna;
#define _particle_ctrl_WiFiAntenna_MIN particle_ctrl_WiFiAntenna_NONE
#define _particle_ctrl_WiFiAntenna_MAX particle_ctrl_WiFiAntenna_AUTO
#define _particle_ctrl_WiFiAntenna_ARRAYSIZE ((particle_ctrl_WiFiAntenna)(particle_ctrl_WiFiAntenna_AUTO+1))

/* Struct definitions */
typedef struct _particle_ctrl_WiFiAntennaConfiguration {
    particle_ctrl_WiFiAntenna antenna;
/* @@protoc_insertion_point(struct:particle_ctrl_WiFiAntennaConfiguration) */
} particle_ctrl_WiFiAntennaConfiguration;

/* Default values for struct fields */

/* Initializer values for message structs */
#define particle_ctrl_WiFiAntennaConfiguration_init_default {(particle_ctrl_WiFiAntenna)0}
#define particle_ctrl_WiFiAntennaConfiguration_init_zero {(particle_ctrl_WiFiAntenna)0}

/* Field tags (for use in manual encoding/decoding) */
#define particle_ctrl_WiFiAntennaConfiguration_antenna_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t particle_ctrl_WiFiAntennaConfiguration_fields[2];

/* Maximum encoded size of messages (where known) */
#define particle_ctrl_WiFiAntennaConfiguration_size 2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CONTROL_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
