
MODULE=wiring
WIRING_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)

DEPENDENCIES = hal services communication system platform dynalib crypto third_party/arduinojson

include ../build/arm-tlm.mk
