/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "control/cloud.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(particle_ctrl_cloud_GetConnectionStatusRequest, particle_ctrl_cloud_GetConnectionStatusRequest, AUTO)


PB_BIND(particle_ctrl_cloud_GetConnectionStatusReply, particle_ctrl_cloud_GetConnectionStatusReply, AUTO)


PB_BIND(particle_ctrl_cloud_ConnectRequest, particle_ctrl_cloud_ConnectRequest, AUTO)


PB_BIND(particle_ctrl_cloud_ConnectReply, particle_ctrl_cloud_ConnectReply, AUTO)


PB_BIND(particle_ctrl_cloud_DisconnectRequest, particle_ctrl_cloud_DisconnectRequest, AUTO)


PB_BIND(particle_ctrl_cloud_DisconnectReply, particle_ctrl_cloud_DisconnectReply, AUTO)




