/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_PARTICLE_CTRL_CLOUD_CONTROL_CLOUD_PB_H_INCLUDED
#define PB_PARTICLE_CTRL_CLOUD_CONTROL_CLOUD_PB_H_INCLUDED
#include <pb.h>
#include "control/extensions.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Make sure values of this enum match the values defined for the diagnostic info */
typedef enum _particle_ctrl_cloud_ConnectionStatus { 
    particle_ctrl_cloud_ConnectionStatus_DISCONNECTED = 0, 
    particle_ctrl_cloud_ConnectionStatus_CONNECTING = 1, 
    particle_ctrl_cloud_ConnectionStatus_CONNECTED = 2, 
    particle_ctrl_cloud_ConnectionStatus_DISCONNECTING = 3 
} particle_ctrl_cloud_ConnectionStatus;

/* Struct definitions */
typedef struct _particle_ctrl_cloud_ConnectReply { 
    char dummy_field;
} particle_ctrl_cloud_ConnectReply;

/* Connect to the cloud */
typedef struct _particle_ctrl_cloud_ConnectRequest { 
    char dummy_field;
} particle_ctrl_cloud_ConnectRequest;

typedef struct _particle_ctrl_cloud_DisconnectReply { 
    char dummy_field;
} particle_ctrl_cloud_DisconnectReply;

/* Disconnect from the cloud */
typedef struct _particle_ctrl_cloud_DisconnectRequest { 
    char dummy_field;
} particle_ctrl_cloud_DisconnectRequest;

/* Get the cloud connection status */
typedef struct _particle_ctrl_cloud_GetConnectionStatusRequest { 
    char dummy_field;
} particle_ctrl_cloud_GetConnectionStatusRequest;

typedef struct _particle_ctrl_cloud_GetConnectionStatusReply { 
    particle_ctrl_cloud_ConnectionStatus status; 
} particle_ctrl_cloud_GetConnectionStatusReply;


/* Helper constants for enums */
#define _particle_ctrl_cloud_ConnectionStatus_MIN particle_ctrl_cloud_ConnectionStatus_DISCONNECTED
#define _particle_ctrl_cloud_ConnectionStatus_MAX particle_ctrl_cloud_ConnectionStatus_DISCONNECTING
#define _particle_ctrl_cloud_ConnectionStatus_ARRAYSIZE ((particle_ctrl_cloud_ConnectionStatus)(particle_ctrl_cloud_ConnectionStatus_DISCONNECTING+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define particle_ctrl_cloud_GetConnectionStatusRequest_init_default {0}
#define particle_ctrl_cloud_GetConnectionStatusReply_init_default {_particle_ctrl_cloud_ConnectionStatus_MIN}
#define particle_ctrl_cloud_ConnectRequest_init_default {0}
#define particle_ctrl_cloud_ConnectReply_init_default {0}
#define particle_ctrl_cloud_DisconnectRequest_init_default {0}
#define particle_ctrl_cloud_DisconnectReply_init_default {0}
#define particle_ctrl_cloud_GetConnectionStatusRequest_init_zero {0}
#define particle_ctrl_cloud_GetConnectionStatusReply_init_zero {_particle_ctrl_cloud_ConnectionStatus_MIN}
#define particle_ctrl_cloud_ConnectRequest_init_zero {0}
#define particle_ctrl_cloud_ConnectReply_init_zero {0}
#define particle_ctrl_cloud_DisconnectRequest_init_zero {0}
#define particle_ctrl_cloud_DisconnectReply_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define particle_ctrl_cloud_GetConnectionStatusReply_status_tag 1

/* Struct field encoding specification for nanopb */
#define particle_ctrl_cloud_GetConnectionStatusRequest_FIELDLIST(X, a) \

#define particle_ctrl_cloud_GetConnectionStatusRequest_CALLBACK NULL
#define particle_ctrl_cloud_GetConnectionStatusRequest_DEFAULT NULL

#define particle_ctrl_cloud_GetConnectionStatusReply_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1)
#define particle_ctrl_cloud_GetConnectionStatusReply_CALLBACK NULL
#define particle_ctrl_cloud_GetConnectionStatusReply_DEFAULT NULL

#define particle_ctrl_cloud_ConnectRequest_FIELDLIST(X, a) \

#define particle_ctrl_cloud_ConnectRequest_CALLBACK NULL
#define particle_ctrl_cloud_ConnectRequest_DEFAULT NULL

#define particle_ctrl_cloud_ConnectReply_FIELDLIST(X, a) \

#define particle_ctrl_cloud_ConnectReply_CALLBACK NULL
#define particle_ctrl_cloud_ConnectReply_DEFAULT NULL

#define particle_ctrl_cloud_DisconnectRequest_FIELDLIST(X, a) \

#define particle_ctrl_cloud_DisconnectRequest_CALLBACK NULL
#define particle_ctrl_cloud_DisconnectRequest_DEFAULT NULL

#define particle_ctrl_cloud_DisconnectReply_FIELDLIST(X, a) \

#define particle_ctrl_cloud_DisconnectReply_CALLBACK NULL
#define particle_ctrl_cloud_DisconnectReply_DEFAULT NULL

extern const pb_msgdesc_t particle_ctrl_cloud_GetConnectionStatusRequest_msg;
extern const pb_msgdesc_t particle_ctrl_cloud_GetConnectionStatusReply_msg;
extern const pb_msgdesc_t particle_ctrl_cloud_ConnectRequest_msg;
extern const pb_msgdesc_t particle_ctrl_cloud_ConnectReply_msg;
extern const pb_msgdesc_t particle_ctrl_cloud_DisconnectRequest_msg;
extern const pb_msgdesc_t particle_ctrl_cloud_DisconnectReply_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define particle_ctrl_cloud_GetConnectionStatusRequest_fields &particle_ctrl_cloud_GetConnectionStatusRequest_msg
#define particle_ctrl_cloud_GetConnectionStatusReply_fields &particle_ctrl_cloud_GetConnectionStatusReply_msg
#define particle_ctrl_cloud_ConnectRequest_fields &particle_ctrl_cloud_ConnectRequest_msg
#define particle_ctrl_cloud_ConnectReply_fields &particle_ctrl_cloud_ConnectReply_msg
#define particle_ctrl_cloud_DisconnectRequest_fields &particle_ctrl_cloud_DisconnectRequest_msg
#define particle_ctrl_cloud_DisconnectReply_fields &particle_ctrl_cloud_DisconnectReply_msg

/* Maximum encoded size of messages (where known) */
#define particle_ctrl_cloud_ConnectReply_size    0
#define particle_ctrl_cloud_ConnectRequest_size  0
#define particle_ctrl_cloud_DisconnectReply_size 0
#define particle_ctrl_cloud_DisconnectRequest_size 0
#define particle_ctrl_cloud_GetConnectionStatusReply_size 2
#define particle_ctrl_cloud_GetConnectionStatusRequest_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
