/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "control/common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(particle_ctrl_Ipv4Address, particle_ctrl_Ipv4Address, AUTO)


PB_BIND(particle_ctrl_Ipv6Address, particle_ctrl_Ipv6Address, AUTO)


PB_BIND(particle_ctrl_IpAddress, particle_ctrl_IpAddress, AUTO)


PB_BIND(particle_ctrl_IPAddress, particle_ctrl_IPAddress, AUTO)





