/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "control/storage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(particle_ctrl_StartFirmwareUpdateRequest, particle_ctrl_StartFirmwareUpdateRequest, AUTO)


PB_BIND(particle_ctrl_StartFirmwareUpdateReply, particle_ctrl_StartFirmwareUpdateReply, AUTO)


PB_BIND(particle_ctrl_FinishFirmwareUpdateRequest, particle_ctrl_FinishFirmwareUpdateRequest, AUTO)


PB_BIND(particle_ctrl_FinishFirmwareUpdateReply, particle_ctrl_FinishFirmwareUpdateReply, AUTO)


PB_BIND(particle_ctrl_CancelFirmwareUpdateRequest, particle_ctrl_CancelFirmwareUpdateRequest, AUTO)


PB_BIND(particle_ctrl_CancelFirmwareUpdateReply, particle_ctrl_CancelFirmwareUpdateReply, AUTO)


PB_BIND(particle_ctrl_FirmwareUpdateDataRequest, particle_ctrl_FirmwareUpdateDataRequest, AUTO)


PB_BIND(particle_ctrl_FirmwareUpdateDataReply, particle_ctrl_FirmwareUpdateDataReply, AUTO)


PB_BIND(particle_ctrl_DescribeStorageRequest, particle_ctrl_DescribeStorageRequest, AUTO)


PB_BIND(particle_ctrl_DescribeStorageReply, particle_ctrl_DescribeStorageReply, AUTO)


PB_BIND(particle_ctrl_DescribeStorageReply_Section, particle_ctrl_DescribeStorageReply_Section, AUTO)


PB_BIND(particle_ctrl_DescribeStorageReply_Section_FirmwareModule, particle_ctrl_DescribeStorageReply_Section_FirmwareModule, AUTO)


PB_BIND(particle_ctrl_DescribeStorageReply_Storage, particle_ctrl_DescribeStorageReply_Storage, AUTO)


PB_BIND(particle_ctrl_ReadSectionDataRequest, particle_ctrl_ReadSectionDataRequest, AUTO)


PB_BIND(particle_ctrl_ReadSectionDataReply, particle_ctrl_ReadSectionDataReply, AUTO)


PB_BIND(particle_ctrl_WriteSectionDataRequest, particle_ctrl_WriteSectionDataRequest, AUTO)


PB_BIND(particle_ctrl_WriteSectionDataReply, particle_ctrl_WriteSectionDataReply, AUTO)


PB_BIND(particle_ctrl_ClearSectionDataRequest, particle_ctrl_ClearSectionDataRequest, AUTO)


PB_BIND(particle_ctrl_ClearSectionDataReply, particle_ctrl_ClearSectionDataReply, AUTO)


PB_BIND(particle_ctrl_GetSectionDataSizeRequest, particle_ctrl_GetSectionDataSizeRequest, AUTO)


PB_BIND(particle_ctrl_GetSectionDataSizeReply, particle_ctrl_GetSectionDataSizeReply, AUTO)


PB_BIND(particle_ctrl_GetModuleInfoRequest, particle_ctrl_GetModuleInfoRequest, AUTO)


PB_BIND(particle_ctrl_GetModuleInfoReply, particle_ctrl_GetModuleInfoReply, AUTO)


PB_BIND(particle_ctrl_GetModuleInfoReply_Dependency, particle_ctrl_GetModuleInfoReply_Dependency, AUTO)


PB_BIND(particle_ctrl_GetModuleInfoReply_Module, particle_ctrl_GetModuleInfoReply_Module, AUTO)









