/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_PARTICLE_CTRL_CONTROL_WIFI_PB_H_INCLUDED
#define PB_PARTICLE_CTRL_CONTROL_WIFI_PB_H_INCLUDED
#include <pb.h>
#include "control/extensions.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _particle_ctrl_WiFiAntenna { 
    particle_ctrl_WiFiAntenna_ANTENNA_NONE = 0, 
    particle_ctrl_WiFiAntenna_INTERNAL = 1, 
    particle_ctrl_WiFiAntenna_EXTERNAL = 2, 
    particle_ctrl_WiFiAntenna_AUTO = 3 
} particle_ctrl_WiFiAntenna;

typedef enum _particle_ctrl_WiFiSecurityType { 
    particle_ctrl_WiFiSecurityType_UNSEC = 0, 
    particle_ctrl_WiFiSecurityType_WEP = 1, 
    particle_ctrl_WiFiSecurityType_WPA = 2, 
    particle_ctrl_WiFiSecurityType_WPA2 = 3, 
    particle_ctrl_WiFiSecurityType_WPA_ENTERPRISE = 4, 
    particle_ctrl_WiFiSecurityType_WPA2_ENTERPRISE = 5, 
    particle_ctrl_WiFiSecurityType_UNKNOWN = 255 
} particle_ctrl_WiFiSecurityType;

typedef enum _particle_ctrl_WiFiSecurityCipher { 
    particle_ctrl_WiFiSecurityCipher_CIPHER_NONE = 0, 
    particle_ctrl_WiFiSecurityCipher_AES = 1, 
    particle_ctrl_WiFiSecurityCipher_TKIP = 2, 
    particle_ctrl_WiFiSecurityCipher_AES_TKIP = 3 
} particle_ctrl_WiFiSecurityCipher;

typedef enum _particle_ctrl_EapType { 
    particle_ctrl_EapType_EAP_TYPE_NONE = 0, 
    particle_ctrl_EapType_TLS = 13, 
    particle_ctrl_EapType_PEAP = 25 
} particle_ctrl_EapType;

/* Struct definitions */
typedef struct _particle_ctrl_WiFiAccessPointList { 
    pb_callback_t aps; 
} particle_ctrl_WiFiAccessPointList;

typedef struct _particle_ctrl_WiFiClearCredentialsReply { 
    char dummy_field;
} particle_ctrl_WiFiClearCredentialsReply;

typedef struct _particle_ctrl_WiFiClearCredentialsRequest { 
    char dummy_field;
} particle_ctrl_WiFiClearCredentialsRequest;

typedef struct _particle_ctrl_WiFiGetAntennaRequest { 
    char dummy_field;
} particle_ctrl_WiFiGetAntennaRequest;

typedef struct _particle_ctrl_WiFiGetCredentialsRequest { 
    char dummy_field;
} particle_ctrl_WiFiGetCredentialsRequest;

typedef struct _particle_ctrl_WiFiScanRequest { 
    char dummy_field;
} particle_ctrl_WiFiScanRequest;

typedef struct _particle_ctrl_WiFiSetAntennaReply { 
    char dummy_field;
} particle_ctrl_WiFiSetAntennaReply;

typedef struct _particle_ctrl_WiFiSetCredentialsReply { 
    char dummy_field;
} particle_ctrl_WiFiSetCredentialsReply;

typedef struct _particle_ctrl_WiFiAccessPoint { 
    char ssid[33]; 
    pb_byte_t bssid[6]; 
    particle_ctrl_WiFiSecurityType security; 
    particle_ctrl_WiFiSecurityCipher cipher; 
    uint32_t channel; 
    int32_t max_data_rate; 
    int32_t rssi; 
    /* Credentials */
    pb_callback_t password; 
    particle_ctrl_EapType eap_type; 
    pb_callback_t inner_identity; 
    pb_callback_t outer_identity; 
    pb_callback_t private_key; 
    pb_callback_t client_certificate; 
    pb_callback_t ca_certificate; 
} particle_ctrl_WiFiAccessPoint;

typedef struct _particle_ctrl_WiFiGetAntennaReply { 
    particle_ctrl_WiFiAntenna antenna; 
} particle_ctrl_WiFiGetAntennaReply;

typedef struct _particle_ctrl_WiFiGetCredentialsReply { 
    particle_ctrl_WiFiAccessPointList list; 
} particle_ctrl_WiFiGetCredentialsReply;

typedef struct _particle_ctrl_WiFiScanReply { 
    particle_ctrl_WiFiAccessPointList list; 
} particle_ctrl_WiFiScanReply;

typedef struct _particle_ctrl_WiFiSetAntennaRequest { 
    particle_ctrl_WiFiAntenna antenna; 
} particle_ctrl_WiFiSetAntennaRequest;

typedef struct _particle_ctrl_WiFiSetCredentialsRequest { 
    particle_ctrl_WiFiAccessPoint ap; 
} particle_ctrl_WiFiSetCredentialsRequest;


/* Helper constants for enums */
#define _particle_ctrl_WiFiAntenna_MIN particle_ctrl_WiFiAntenna_ANTENNA_NONE
#define _particle_ctrl_WiFiAntenna_MAX particle_ctrl_WiFiAntenna_AUTO
#define _particle_ctrl_WiFiAntenna_ARRAYSIZE ((particle_ctrl_WiFiAntenna)(particle_ctrl_WiFiAntenna_AUTO+1))

#define _particle_ctrl_WiFiSecurityType_MIN particle_ctrl_WiFiSecurityType_UNSEC
#define _particle_ctrl_WiFiSecurityType_MAX particle_ctrl_WiFiSecurityType_UNKNOWN
#define _particle_ctrl_WiFiSecurityType_ARRAYSIZE ((particle_ctrl_WiFiSecurityType)(particle_ctrl_WiFiSecurityType_UNKNOWN+1))

#define _particle_ctrl_WiFiSecurityCipher_MIN particle_ctrl_WiFiSecurityCipher_CIPHER_NONE
#define _particle_ctrl_WiFiSecurityCipher_MAX particle_ctrl_WiFiSecurityCipher_AES_TKIP
#define _particle_ctrl_WiFiSecurityCipher_ARRAYSIZE ((particle_ctrl_WiFiSecurityCipher)(particle_ctrl_WiFiSecurityCipher_AES_TKIP+1))

#define _particle_ctrl_EapType_MIN particle_ctrl_EapType_EAP_TYPE_NONE
#define _particle_ctrl_EapType_MAX particle_ctrl_EapType_PEAP
#define _particle_ctrl_EapType_ARRAYSIZE ((particle_ctrl_EapType)(particle_ctrl_EapType_PEAP+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define particle_ctrl_WiFiGetAntennaRequest_init_default {0}
#define particle_ctrl_WiFiGetAntennaReply_init_default {_particle_ctrl_WiFiAntenna_MIN}
#define particle_ctrl_WiFiSetAntennaRequest_init_default {_particle_ctrl_WiFiAntenna_MIN}
#define particle_ctrl_WiFiSetAntennaReply_init_default {0}
#define particle_ctrl_WiFiScanRequest_init_default {0}
#define particle_ctrl_WiFiScanReply_init_default {particle_ctrl_WiFiAccessPointList_init_default}
#define particle_ctrl_WiFiGetCredentialsRequest_init_default {0}
#define particle_ctrl_WiFiGetCredentialsReply_init_default {particle_ctrl_WiFiAccessPointList_init_default}
#define particle_ctrl_WiFiSetCredentialsRequest_init_default {particle_ctrl_WiFiAccessPoint_init_default}
#define particle_ctrl_WiFiSetCredentialsReply_init_default {0}
#define particle_ctrl_WiFiClearCredentialsRequest_init_default {0}
#define particle_ctrl_WiFiClearCredentialsReply_init_default {0}
#define particle_ctrl_WiFiAccessPoint_init_default {"", {0}, _particle_ctrl_WiFiSecurityType_MIN, _particle_ctrl_WiFiSecurityCipher_MIN, 0, 0, 0, {{NULL}, NULL}, _particle_ctrl_EapType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define particle_ctrl_WiFiAccessPointList_init_default {{{NULL}, NULL}}
#define particle_ctrl_WiFiGetAntennaRequest_init_zero {0}
#define particle_ctrl_WiFiGetAntennaReply_init_zero {_particle_ctrl_WiFiAntenna_MIN}
#define particle_ctrl_WiFiSetAntennaRequest_init_zero {_particle_ctrl_WiFiAntenna_MIN}
#define particle_ctrl_WiFiSetAntennaReply_init_zero {0}
#define particle_ctrl_WiFiScanRequest_init_zero  {0}
#define particle_ctrl_WiFiScanReply_init_zero    {particle_ctrl_WiFiAccessPointList_init_zero}
#define particle_ctrl_WiFiGetCredentialsRequest_init_zero {0}
#define particle_ctrl_WiFiGetCredentialsReply_init_zero {particle_ctrl_WiFiAccessPointList_init_zero}
#define particle_ctrl_WiFiSetCredentialsRequest_init_zero {particle_ctrl_WiFiAccessPoint_init_zero}
#define particle_ctrl_WiFiSetCredentialsReply_init_zero {0}
#define particle_ctrl_WiFiClearCredentialsRequest_init_zero {0}
#define particle_ctrl_WiFiClearCredentialsReply_init_zero {0}
#define particle_ctrl_WiFiAccessPoint_init_zero  {"", {0}, _particle_ctrl_WiFiSecurityType_MIN, _particle_ctrl_WiFiSecurityCipher_MIN, 0, 0, 0, {{NULL}, NULL}, _particle_ctrl_EapType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define particle_ctrl_WiFiAccessPointList_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define particle_ctrl_WiFiAccessPointList_aps_tag 1
#define particle_ctrl_WiFiAccessPoint_ssid_tag   1
#define particle_ctrl_WiFiAccessPoint_bssid_tag  2
#define particle_ctrl_WiFiAccessPoint_security_tag 3
#define particle_ctrl_WiFiAccessPoint_cipher_tag 4
#define particle_ctrl_WiFiAccessPoint_channel_tag 5
#define particle_ctrl_WiFiAccessPoint_max_data_rate_tag 6
#define particle_ctrl_WiFiAccessPoint_rssi_tag   7
#define particle_ctrl_WiFiAccessPoint_password_tag 8
#define particle_ctrl_WiFiAccessPoint_eap_type_tag 9
#define particle_ctrl_WiFiAccessPoint_inner_identity_tag 10
#define particle_ctrl_WiFiAccessPoint_outer_identity_tag 11
#define particle_ctrl_WiFiAccessPoint_private_key_tag 12
#define particle_ctrl_WiFiAccessPoint_client_certificate_tag 13
#define particle_ctrl_WiFiAccessPoint_ca_certificate_tag 14
#define particle_ctrl_WiFiGetAntennaReply_antenna_tag 1
#define particle_ctrl_WiFiGetCredentialsReply_list_tag 1
#define particle_ctrl_WiFiScanReply_list_tag     1
#define particle_ctrl_WiFiSetAntennaRequest_antenna_tag 1
#define particle_ctrl_WiFiSetCredentialsRequest_ap_tag 1

/* Struct field encoding specification for nanopb */
#define particle_ctrl_WiFiGetAntennaRequest_FIELDLIST(X, a) \

#define particle_ctrl_WiFiGetAntennaRequest_CALLBACK NULL
#define particle_ctrl_WiFiGetAntennaRequest_DEFAULT NULL

#define particle_ctrl_WiFiGetAntennaReply_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    antenna,           1)
#define particle_ctrl_WiFiGetAntennaReply_CALLBACK NULL
#define particle_ctrl_WiFiGetAntennaReply_DEFAULT NULL

#define particle_ctrl_WiFiSetAntennaRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    antenna,           1)
#define particle_ctrl_WiFiSetAntennaRequest_CALLBACK NULL
#define particle_ctrl_WiFiSetAntennaRequest_DEFAULT NULL

#define particle_ctrl_WiFiSetAntennaReply_FIELDLIST(X, a) \

#define particle_ctrl_WiFiSetAntennaReply_CALLBACK NULL
#define particle_ctrl_WiFiSetAntennaReply_DEFAULT NULL

#define particle_ctrl_WiFiScanRequest_FIELDLIST(X, a) \

#define particle_ctrl_WiFiScanRequest_CALLBACK NULL
#define particle_ctrl_WiFiScanRequest_DEFAULT NULL

#define particle_ctrl_WiFiScanReply_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  list,              1)
#define particle_ctrl_WiFiScanReply_CALLBACK NULL
#define particle_ctrl_WiFiScanReply_DEFAULT NULL
#define particle_ctrl_WiFiScanReply_list_MSGTYPE particle_ctrl_WiFiAccessPointList

#define particle_ctrl_WiFiGetCredentialsRequest_FIELDLIST(X, a) \

#define particle_ctrl_WiFiGetCredentialsRequest_CALLBACK NULL
#define particle_ctrl_WiFiGetCredentialsRequest_DEFAULT NULL

#define particle_ctrl_WiFiGetCredentialsReply_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  list,              1)
#define particle_ctrl_WiFiGetCredentialsReply_CALLBACK NULL
#define particle_ctrl_WiFiGetCredentialsReply_DEFAULT NULL
#define particle_ctrl_WiFiGetCredentialsReply_list_MSGTYPE particle_ctrl_WiFiAccessPointList

#define particle_ctrl_WiFiSetCredentialsRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  ap,                1)
#define particle_ctrl_WiFiSetCredentialsRequest_CALLBACK NULL
#define particle_ctrl_WiFiSetCredentialsRequest_DEFAULT NULL
#define particle_ctrl_WiFiSetCredentialsRequest_ap_MSGTYPE particle_ctrl_WiFiAccessPoint

#define particle_ctrl_WiFiSetCredentialsReply_FIELDLIST(X, a) \

#define particle_ctrl_WiFiSetCredentialsReply_CALLBACK NULL
#define particle_ctrl_WiFiSetCredentialsReply_DEFAULT NULL

#define particle_ctrl_WiFiClearCredentialsRequest_FIELDLIST(X, a) \

#define particle_ctrl_WiFiClearCredentialsRequest_CALLBACK NULL
#define particle_ctrl_WiFiClearCredentialsRequest_DEFAULT NULL

#define particle_ctrl_WiFiClearCredentialsReply_FIELDLIST(X, a) \

#define particle_ctrl_WiFiClearCredentialsReply_CALLBACK NULL
#define particle_ctrl_WiFiClearCredentialsReply_DEFAULT NULL

#define particle_ctrl_WiFiAccessPoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, bssid,             2) \
X(a, STATIC,   SINGULAR, UENUM,    security,          3) \
X(a, STATIC,   SINGULAR, UENUM,    cipher,            4) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           5) \
X(a, STATIC,   SINGULAR, INT32,    max_data_rate,     6) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              7) \
X(a, CALLBACK, SINGULAR, STRING,   password,          8) \
X(a, STATIC,   SINGULAR, UENUM,    eap_type,          9) \
X(a, CALLBACK, SINGULAR, STRING,   inner_identity,   10) \
X(a, CALLBACK, SINGULAR, STRING,   outer_identity,   11) \
X(a, CALLBACK, SINGULAR, BYTES,    private_key,      12) \
X(a, CALLBACK, SINGULAR, BYTES,    client_certificate,  13) \
X(a, CALLBACK, SINGULAR, BYTES,    ca_certificate,   14)
#define particle_ctrl_WiFiAccessPoint_CALLBACK pb_default_field_callback
#define particle_ctrl_WiFiAccessPoint_DEFAULT NULL

#define particle_ctrl_WiFiAccessPointList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  aps,               1)
#define particle_ctrl_WiFiAccessPointList_CALLBACK pb_default_field_callback
#define particle_ctrl_WiFiAccessPointList_DEFAULT NULL
#define particle_ctrl_WiFiAccessPointList_aps_MSGTYPE particle_ctrl_WiFiAccessPoint

extern const pb_msgdesc_t particle_ctrl_WiFiGetAntennaRequest_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiGetAntennaReply_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiSetAntennaRequest_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiSetAntennaReply_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiScanRequest_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiScanReply_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiGetCredentialsRequest_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiGetCredentialsReply_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiSetCredentialsRequest_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiSetCredentialsReply_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiClearCredentialsRequest_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiClearCredentialsReply_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiAccessPoint_msg;
extern const pb_msgdesc_t particle_ctrl_WiFiAccessPointList_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define particle_ctrl_WiFiGetAntennaRequest_fields &particle_ctrl_WiFiGetAntennaRequest_msg
#define particle_ctrl_WiFiGetAntennaReply_fields &particle_ctrl_WiFiGetAntennaReply_msg
#define particle_ctrl_WiFiSetAntennaRequest_fields &particle_ctrl_WiFiSetAntennaRequest_msg
#define particle_ctrl_WiFiSetAntennaReply_fields &particle_ctrl_WiFiSetAntennaReply_msg
#define particle_ctrl_WiFiScanRequest_fields &particle_ctrl_WiFiScanRequest_msg
#define particle_ctrl_WiFiScanReply_fields &particle_ctrl_WiFiScanReply_msg
#define particle_ctrl_WiFiGetCredentialsRequest_fields &particle_ctrl_WiFiGetCredentialsRequest_msg
#define particle_ctrl_WiFiGetCredentialsReply_fields &particle_ctrl_WiFiGetCredentialsReply_msg
#define particle_ctrl_WiFiSetCredentialsRequest_fields &particle_ctrl_WiFiSetCredentialsRequest_msg
#define particle_ctrl_WiFiSetCredentialsReply_fields &particle_ctrl_WiFiSetCredentialsReply_msg
#define particle_ctrl_WiFiClearCredentialsRequest_fields &particle_ctrl_WiFiClearCredentialsRequest_msg
#define particle_ctrl_WiFiClearCredentialsReply_fields &particle_ctrl_WiFiClearCredentialsReply_msg
#define particle_ctrl_WiFiAccessPoint_fields &particle_ctrl_WiFiAccessPoint_msg
#define particle_ctrl_WiFiAccessPointList_fields &particle_ctrl_WiFiAccessPointList_msg

/* Maximum encoded size of messages (where known) */
/* particle_ctrl_WiFiScanReply_size depends on runtime parameters */
/* particle_ctrl_WiFiGetCredentialsReply_size depends on runtime parameters */
/* particle_ctrl_WiFiSetCredentialsRequest_size depends on runtime parameters */
/* particle_ctrl_WiFiAccessPoint_size depends on runtime parameters */
/* particle_ctrl_WiFiAccessPointList_size depends on runtime parameters */
#define particle_ctrl_WiFiClearCredentialsReply_size 0
#define particle_ctrl_WiFiClearCredentialsRequest_size 0
#define particle_ctrl_WiFiGetAntennaReply_size   2
#define particle_ctrl_WiFiGetAntennaRequest_size 0
#define particle_ctrl_WiFiGetCredentialsRequest_size 0
#define particle_ctrl_WiFiScanRequest_size       0
#define particle_ctrl_WiFiSetAntennaReply_size   0
#define particle_ctrl_WiFiSetAntennaRequest_size 2
#define particle_ctrl_WiFiSetCredentialsReply_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
