/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "control/wifi_new.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(particle_ctrl_wifi_Credentials, particle_ctrl_wifi_Credentials, AUTO)


PB_BIND(particle_ctrl_wifi_JoinNewNetworkRequest, particle_ctrl_wifi_JoinNewNetworkRequest, 2)


PB_BIND(particle_ctrl_wifi_JoinNewNetworkReply, particle_ctrl_wifi_JoinNewNetworkReply, AUTO)


PB_BIND(particle_ctrl_wifi_JoinKnownNetworkRequest, particle_ctrl_wifi_JoinKnownNetworkRequest, AUTO)


PB_BIND(particle_ctrl_wifi_JoinKnownNetworkReply, particle_ctrl_wifi_JoinKnownNetworkReply, AUTO)


PB_BIND(particle_ctrl_wifi_GetKnownNetworksRequest, particle_ctrl_wifi_GetKnownNetworksRequest, AUTO)


PB_BIND(particle_ctrl_wifi_GetKnownNetworksReply, particle_ctrl_wifi_GetKnownNetworksReply, AUTO)


PB_BIND(particle_ctrl_wifi_GetKnownNetworksReply_Network, particle_ctrl_wifi_GetKnownNetworksReply_Network, AUTO)


PB_BIND(particle_ctrl_wifi_RemoveKnownNetworkRequest, particle_ctrl_wifi_RemoveKnownNetworkRequest, AUTO)


PB_BIND(particle_ctrl_wifi_RemoveKnownNetworkReply, particle_ctrl_wifi_RemoveKnownNetworkReply, AUTO)


PB_BIND(particle_ctrl_wifi_ClearKnownNetworksRequest, particle_ctrl_wifi_ClearKnownNetworksRequest, AUTO)


PB_BIND(particle_ctrl_wifi_ClearKnownNetworksReply, particle_ctrl_wifi_ClearKnownNetworksReply, AUTO)


PB_BIND(particle_ctrl_wifi_GetCurrentNetworkRequest, particle_ctrl_wifi_GetCurrentNetworkRequest, AUTO)


PB_BIND(particle_ctrl_wifi_GetCurrentNetworkReply, particle_ctrl_wifi_GetCurrentNetworkReply, AUTO)


PB_BIND(particle_ctrl_wifi_ScanNetworksRequest, particle_ctrl_wifi_ScanNetworksRequest, AUTO)


PB_BIND(particle_ctrl_wifi_ScanNetworksReply, particle_ctrl_wifi_ScanNetworksReply, AUTO)


PB_BIND(particle_ctrl_wifi_ScanNetworksReply_Network, particle_ctrl_wifi_ScanNetworksReply_Network, AUTO)





