ifeq ($(MODULE),prebootloader)

ASRC += $(COMMON_BUILD)/arm/startup/startup_$(STM32_DEVICE_LC).S
ASFLAGS += -I$(COMMON_BUILD)/arm/startup

# Linker flags
LDFLAGS += -Wl,-Map,$(TARGET_BASE).map

LINKER_DEPS += $(COMMON_BUILD)/arm/linker/linker_module_start.ld
LINKER_DEPS += $(COMMON_BUILD)/arm/linker/linker_module_end.ld
LINKER_DEPS += $(COMMON_BUILD)/arm/linker/linker_module_info.ld

ifeq (,$(PREBOOTLOADER_MODULE_DEPENDENCY))
PREBOOTLOADER_MODULE_DEPENDENCY=0,0,0
endif

ifeq (,$(PREBOOTLOADER_MODULE_DEPENDENCY2))
PREBOOTLOADER_MODULE_DEPENDENCY2=0,0,0
endif

ifeq (,$(PREBOOTLOADER_MODULE_INDEX))
PREBOOTLOADER_MODULE_INDEX=2
endif

GLOBAL_DEFINES += PREBOOTLOADER_VERSION=$(PREBOOTLOADER_VERSION)
GLOBAL_DEFINES += MODULE_VERSION=$(PREBOOTLOADER_VERSION)
GLOBAL_DEFINES += MODULE_FUNCTION=$(MODULE_FUNCTION_BOOTLOADER)
GLOBAL_DEFINES += MODULE_DEPENDENCY=$(PREBOOTLOADER_MODULE_DEPENDENCY)
GLOBAL_DEFINES += MODULE_DEPENDENCY2=$(PREBOOTLOADER_MODULE_DEPENDENCY2)
GLOBAL_DEFINES += MODULE_INDEX=$(PREBOOTLOADER_MODULE_INDEX)

# select sources from platform

# import common main.c under bootloader/src
include $(PREBOOTLOADER_MODULE_PATH)/src/sources.mk

# import the sources from the platform
include $(call rwildcard,$(PREBOOTLOADER_MODULE_PATH)/src/$(PLATFORM_NAME)/,sources.mk)

endif