DYNALIB_MODULE_NAME=dynalib
DYNALIB_MODULE_PATH ?= $(PROJECT_ROOT)/$(DYNALIB_MODULE_NAME)
include $(call rwildcard,$(DYNALIB_MODULE_PATH)/,include.mk)

DYNALIB_BUILD_PATH_EXT=$(ARCH)
DYNALIB_LIB_DIR = $(BUILD_PATH_BASE)/$(DYNALIB_MODULE_NAME)/$(DYNALIB_BUILD_PATH_EXT)
DYNALIB_LIB_DEP = $(DYNALIB_LIB_DIR)/lib$(DYNALIB_MODULE_NAME).a
