# Makefile that included by all modules - this defines the layout of the various modules

SHARED_MODULAR=$(PROJECT_ROOT)/modules/shared/rtl872x

MODULAR_FIRMWARE=y
# propagate to sub makes
MAKE_ARGS += MODULAR_FIRMWARE=y
# FIXME
USER_FIRMWARE_IMAGE_SIZE=0x100000
USER_FIRMWARE_IMAGE_LOCATION=0x8116000

# Ensure these defines are passed to all sub makefiles
GLOBAL_DEFINES += USER_FIRMWARE_IMAGE_SIZE=$(USER_FIRMWARE_IMAGE_SIZE)
GLOBAL_DEFINES += USER_FIRMWARE_IMAGE_LOCATION=$(USER_FIRMWARE_IMAGE_LOCATION)
GLOBAL_DEFINES += MODULAR_FIRMWARE=1

export PLATFORM_ID ?= 32