#ifndef __INCLUDE_NUTTX_VERSION_H
#define __INCLUDE_NUTTX_VERSION_H

#define CONFIG_VERSION_STRING "7.8"
#define CONFIG_VERSION_MAJOR 7
#define CONFIG_VERSION_MINOR 8
#define CONFIG_VERSION_BUILD "0"

#define CONFIG_VERSION ((CONFIG_VERSION_MAJOR << 8) | (CONFIG_VERSION_MINOR))

#endif /* __INCLUDE_NUTTX_VERSION_H */
