/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Oct 10 13:06:10 2018. */

#include "cellular.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t particle_ctrl_cellular_AccessPoint_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, particle_ctrl_cellular_AccessPoint, apn, apn, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, particle_ctrl_cellular_AccessPoint, user, apn, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, particle_ctrl_cellular_AccessPoint, password, user, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, particle_ctrl_cellular_AccessPoint, use_defaults, password, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
