/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Thu Dec 30 21:55:48 2021. */

#include "config.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t particle_ctrl_GetDeviceIdRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetDeviceIdReply_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, particle_ctrl_GetDeviceIdReply, id, id, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetSerialNumberRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetSerialNumberReply_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, particle_ctrl_GetSerialNumberReply, serial, serial, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetSystemVersionRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetSystemVersionReply_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, particle_ctrl_GetSystemVersionReply, version, version, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetNcpFirmwareVersionRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetNcpFirmwareVersionReply_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, particle_ctrl_GetNcpFirmwareVersionReply, version, version, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, particle_ctrl_GetNcpFirmwareVersionReply, module_version, version, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetSystemCapabilitiesRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetSystemCapabilitiesReply_fields[2] = {
    PB_FIELD(  1, FIXED32 , SINGULAR, STATIC  , FIRST, particle_ctrl_GetSystemCapabilitiesReply, flags, flags, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetClaimCodeRequest_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, particle_ctrl_SetClaimCodeRequest, code, code, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetClaimCodeReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_IsClaimedRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_IsClaimedReply_fields[2] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, particle_ctrl_IsClaimedReply, claimed, claimed, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetServerAddressRequest_fields[3] = {
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , FIRST, particle_ctrl_SetServerAddressRequest, address, address, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, particle_ctrl_SetServerAddressRequest, port, address, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetServerAddressReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetServerAddressRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetServerAddressReply_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, particle_ctrl_GetServerAddressReply, address, address, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, particle_ctrl_GetServerAddressReply, port, address, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetSoftApSsidRequest_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, particle_ctrl_SetSoftApSsidRequest, prefix, prefix, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, particle_ctrl_SetSoftApSsidRequest, suffix, prefix, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetSoftApSsidReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_StartListeningModeRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_StartListeningModeReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_StopListeningModeRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_StopListeningModeReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetDeviceModeRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetDeviceModeReply_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, particle_ctrl_GetDeviceModeReply, mode, mode, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetDeviceSetupDoneRequest_fields[2] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, particle_ctrl_SetDeviceSetupDoneRequest, done, done, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetDeviceSetupDoneReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_IsDeviceSetupDoneRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_IsDeviceSetupDoneReply_fields[2] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, particle_ctrl_IsDeviceSetupDoneReply, done, done, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetStartupModeRequest_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, particle_ctrl_SetStartupModeRequest, mode, mode, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetStartupModeReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SystemResetRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SystemResetReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetFeatureRequest_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, particle_ctrl_SetFeatureRequest, feature, feature, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, particle_ctrl_SetFeatureRequest, enabled, feature, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetFeatureReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetFeatureRequest_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, particle_ctrl_GetFeatureRequest, feature, feature, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetFeatureReply_fields[2] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, particle_ctrl_GetFeatureReply, enabled, enabled, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_StartNyanSignalRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_StartNyanSignalReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_StopNyanSignalRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_StopNyanSignalReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetDevicePrivateKeyRequest_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, particle_ctrl_SetDevicePrivateKeyRequest, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetDevicePrivateKeyReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetDevicePrivateKeyRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetDevicePrivateKeyReply_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, particle_ctrl_GetDevicePrivateKeyReply, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetDevicePublicKeyRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetDevicePublicKeyReply_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, particle_ctrl_GetDevicePublicKeyReply, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetServerPublicKeyRequest_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, particle_ctrl_SetServerPublicKeyRequest, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_SetServerPublicKeyReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetServerPublicKeyRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetServerPublicKeyReply_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, particle_ctrl_GetServerPublicKeyReply, data, data, 0),
    PB_LAST_FIELD
};





/* @@protoc_insertion_point(eof) */
