/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Fri May 11 23:57:33 2018. */

#ifndef PB_EXTENSIONS_PB_H_INCLUDED
#define PB_EXTENSIONS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Extensions */
/* Extension field type_id was skipped because only "optional"
   type of extension fields is currently supported. */
/* Extension field int_value was skipped because only "optional"
   type of extension fields is currently supported. */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
