/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Fri May 11 23:57:33 2018. */

#include "extensions.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif






/* @@protoc_insertion_point(eof) */
