/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Thu Sep 20 19:41:50 2018. */

#ifndef PB_PARTICLE_FIRMWARE_INTERNAL_PB_H_INCLUDED
#define PB_PARTICLE_FIRMWARE_INTERNAL_PB_H_INCLUDED
#include <pb.h>

#include "wifi_new.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _particle_firmware_WifiConfig {
    pb_callback_t networks;
/* @@protoc_insertion_point(struct:particle_firmware_WifiConfig) */
} particle_firmware_WifiConfig;

typedef struct _particle_firmware_WifiConfig_Network {
    pb_callback_t ssid;
    particle_ctrl_wifi_Security security;
    particle_ctrl_wifi_Credentials credentials;
/* @@protoc_insertion_point(struct:particle_firmware_WifiConfig_Network) */
} particle_firmware_WifiConfig_Network;

/* Default values for struct fields */

/* Initializer values for message structs */
#define particle_firmware_WifiConfig_init_default {{{NULL}, NULL}}
#define particle_firmware_WifiConfig_Network_init_default {{{NULL}, NULL}, (particle_ctrl_wifi_Security)0, particle_ctrl_wifi_Credentials_init_default}
#define particle_firmware_WifiConfig_init_zero   {{{NULL}, NULL}}
#define particle_firmware_WifiConfig_Network_init_zero {{{NULL}, NULL}, (particle_ctrl_wifi_Security)0, particle_ctrl_wifi_Credentials_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define particle_firmware_WifiConfig_networks_tag 1
#define particle_firmware_WifiConfig_Network_ssid_tag 1
#define particle_firmware_WifiConfig_Network_security_tag 2
#define particle_firmware_WifiConfig_Network_credentials_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t particle_firmware_WifiConfig_fields[2];
extern const pb_field_t particle_firmware_WifiConfig_Network_fields[4];

/* Maximum encoded size of messages (where known) */
/* particle_firmware_WifiConfig_size depends on runtime parameters */
/* particle_firmware_WifiConfig_Network_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define INTERNAL_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
