/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Fri Jan 12 21:30:44 2018. */

#include "storage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t particle_ctrl_StartFirmwareUpdateRequest_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, particle_ctrl_StartFirmwareUpdateRequest, size, size, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_StartFirmwareUpdateReply_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, particle_ctrl_StartFirmwareUpdateReply, chunk_size, chunk_size, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_FinishFirmwareUpdateRequest_fields[2] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, particle_ctrl_FinishFirmwareUpdateRequest, validate_only, validate_only, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_FinishFirmwareUpdateReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_CancelFirmwareUpdateRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_CancelFirmwareUpdateReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_FirmwareUpdateDataRequest_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, particle_ctrl_FirmwareUpdateDataRequest, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_FirmwareUpdateDataReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_DescribeStorageRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_DescribeStorageReply_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, particle_ctrl_DescribeStorageReply, storage, storage, &particle_ctrl_DescribeStorageReply_Storage_fields),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_DescribeStorageReply_Section_fields[5] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, particle_ctrl_DescribeStorageReply_Section, type, type, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, particle_ctrl_DescribeStorageReply_Section, size, type, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, particle_ctrl_DescribeStorageReply_Section, flags, size, 0),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, particle_ctrl_DescribeStorageReply_Section, firmware_module, flags, &particle_ctrl_DescribeStorageReply_Section_FirmwareModule_fields),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_DescribeStorageReply_Section_FirmwareModule_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, particle_ctrl_DescribeStorageReply_Section_FirmwareModule, type, type, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, particle_ctrl_DescribeStorageReply_Section_FirmwareModule, index, type, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_DescribeStorageReply_Storage_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, particle_ctrl_DescribeStorageReply_Storage, type, type, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, particle_ctrl_DescribeStorageReply_Storage, flags, type, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, particle_ctrl_DescribeStorageReply_Storage, sections, flags, &particle_ctrl_DescribeStorageReply_Section_fields),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_ReadSectionDataRequest_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, particle_ctrl_ReadSectionDataRequest, storage, storage, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, particle_ctrl_ReadSectionDataRequest, section, storage, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, particle_ctrl_ReadSectionDataRequest, offset, section, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, particle_ctrl_ReadSectionDataRequest, size, offset, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_ReadSectionDataReply_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, particle_ctrl_ReadSectionDataReply, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_WriteSectionDataRequest_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, particle_ctrl_WriteSectionDataRequest, storage, storage, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, particle_ctrl_WriteSectionDataRequest, section, storage, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, particle_ctrl_WriteSectionDataRequest, offset, section, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, particle_ctrl_WriteSectionDataRequest, data, offset, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_WriteSectionDataReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_ClearSectionDataRequest_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, particle_ctrl_ClearSectionDataRequest, storage, storage, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, particle_ctrl_ClearSectionDataRequest, section, storage, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_ClearSectionDataReply_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetSectionDataSizeRequest_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, particle_ctrl_GetSectionDataSizeRequest, storage, storage, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, particle_ctrl_GetSectionDataSizeRequest, section, storage, 0),
    PB_LAST_FIELD
};

const pb_field_t particle_ctrl_GetSectionDataSizeReply_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, particle_ctrl_GetSectionDataSizeReply, size, size, 0),
    PB_LAST_FIELD
};






/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(particle_ctrl_DescribeStorageReply_Section, firmware_module) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_particle_ctrl_StartFirmwareUpdateRequest_particle_ctrl_StartFirmwareUpdateReply_particle_ctrl_FinishFirmwareUpdateRequest_particle_ctrl_FinishFirmwareUpdateReply_particle_ctrl_CancelFirmwareUpdateRequest_particle_ctrl_CancelFirmwareUpdateReply_particle_ctrl_FirmwareUpdateDataRequest_particle_ctrl_FirmwareUpdateDataReply_particle_ctrl_DescribeStorageRequest_particle_ctrl_DescribeStorageReply_particle_ctrl_DescribeStorageReply_Section_particle_ctrl_DescribeStorageReply_Section_FirmwareModule_particle_ctrl_DescribeStorageReply_Storage_particle_ctrl_ReadSectionDataRequest_particle_ctrl_ReadSectionDataReply_particle_ctrl_WriteSectionDataRequest_particle_ctrl_WriteSectionDataReply_particle_ctrl_ClearSectionDataRequest_particle_ctrl_ClearSectionDataReply_particle_ctrl_GetSectionDataSizeRequest_particle_ctrl_GetSectionDataSizeReply)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(particle_ctrl_DescribeStorageReply_Section, firmware_module) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_particle_ctrl_StartFirmwareUpdateRequest_particle_ctrl_StartFirmwareUpdateReply_particle_ctrl_FinishFirmwareUpdateRequest_particle_ctrl_FinishFirmwareUpdateReply_particle_ctrl_CancelFirmwareUpdateRequest_particle_ctrl_CancelFirmwareUpdateReply_particle_ctrl_FirmwareUpdateDataRequest_particle_ctrl_FirmwareUpdateDataReply_particle_ctrl_DescribeStorageRequest_particle_ctrl_DescribeStorageReply_particle_ctrl_DescribeStorageReply_Section_particle_ctrl_DescribeStorageReply_Section_FirmwareModule_particle_ctrl_DescribeStorageReply_Storage_particle_ctrl_ReadSectionDataRequest_particle_ctrl_ReadSectionDataReply_particle_ctrl_WriteSectionDataRequest_particle_ctrl_WriteSectionDataReply_particle_ctrl_ClearSectionDataRequest_particle_ctrl_ClearSectionDataReply_particle_ctrl_GetSectionDataSizeRequest_particle_ctrl_GetSectionDataSizeReply)
#endif


/* @@protoc_insertion_point(eof) */
