SERVICES_MODULE_NAME = services
SERVICES_MODULE_PATH ?= $(PROJECT_ROOT)/$(SERVICES_MODULE_NAME)
include $(call rwildcard,$(SERVICES_MODULE_PATH)/,include.mk)

SERVICES_BUILD_PATH_EXT=$(BUILD_TARGET_PLATFORM)
SERVICES_LIB_DIR = $(BUILD_PATH_BASE)/$(SERVICES_MODULE_NAME)/$(SERVICES_BUILD_PATH_EXT)
SERVICES_LIB_DEP = $(SERVICES_LIB_DIR)/lib$(SERVICES_MODULE_NAME).a
