
MODULE=services
SERVICES_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT=$(SERVICES_BUILD_PATH_EXT)
DEPENDENCIES = platform hal wiring third_party/nanopb dynalib
MAKE_DEPENDENCIES = third_party/nanopb

include ../build/arm-tlm.mk
