
MODULE=services
SERVICES_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT=$(SERVICES_BUILD_PATH_EXT)
DEPENDENCIES = platform hal system wiring dynalib
MAKE_DEPENDENCIES =

include ../build/arm-tlm.mk
