CRYPTO_DYNALIB_MODULE_NAME = crypto-dynalib
CRYPTO_DYNALIB_MODULE_PATH ?= $(PROJECT_ROOT)/$(CRYPTO_DYNALIB_MODULE_NAME)
include $(call rwildcard,$(CRYPTO_DYNALIB_MODULE_PATH)/,include.mk)

CRYPTO_DYNALIB_BUILD_PATH_EXT=$(BUILD_TARGET_PLATFORM)
CRYPTO_DYNALIB_LIB_DIR = $(BUILD_PATH_BASE)/$(CRYPTO_DYNALIB_MODULE_NAME)/$(CRYPTO_DYNALIB_BUILD_PATH_EXT)
CRYPTO_DYNALIB_LIB_DEP = $(CRYPTO_DYNALIB_LIB_DIR)/lib$(CRYPTO_DYNALIB_MODULE_NAME).a

