
MODULE=crypto-dynalib
CRYPTO_DYNALIB_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT=$(CRYPTO_DYNALIB_BUILD_PATH_EXT)

DEPENDENCIES = crypto dynalib hal

include ../build/arm-tlm.mk
