SYSTEM_DYNALIB_MODULE_NAME = system-dynalib
SYSTEM_DYNALIB_MODULE_PATH ?= $(PROJECT_ROOT)/$(SYSTEM_DYNALIB_MODULE_NAME)
include $(call rwildcard,$(SYSTEM_DYNALIB_MODULE_PATH)/,include.mk)
SYSTEM_DYNALIB_BUILD_PATH_EXT=$(BUILD_TARGET_PLATFORM)
SYSTEM_DYNALIB_LIB_DIR = $(BUILD_PATH_BASE)/system-dynalib/$(SYSTEM_DYNALIB_BUILD_PATH_EXT)
SYSTEM_DYNALIB_LIB_DEP = $(SYSTEM_DYNALIB_LIB_DIR)/libsystem-dynalib.a
