
MODULE=platform
PLATFORM_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT = $(PLATFORM_BUILD_PATH_EXT)

DEPENDENCIES = services hal dynalib

include ../build/arm-tlm.mk
