SERVICES_DYNALIB_MODULE_NAME = services-dynalib
SERVICES_DYNALIB_MODULE_PATH ?= $(PROJECT_ROOT)/$(SERVICES_DYNALIB_MODULE_NAME)
include $(call rwildcard,$(SERVICES_DYNALIB_MODULE_PATH)/,include.mk)

SERVICES_DYNALIB_BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)
SERVICES_DYNALIB_LIB_DIR = $(BUILD_PATH_BASE)/$(SERVICES_DYNALIB_MODULE_NAME)/$(SERVICES_DYNALIB_BUILD_PATH_EXT)
SERVICES_DYNALIB_LIB_DEP = $(SERVICES_DYNALIB_LIB_DIR)/lib$(SERVICES_DYNALIB_MODULE_NAME).a
