/*
 * Copyright (c) 2026 Particle Industries, Inc.  All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

enum class CellularAccessTechnology {
    NONE = -1,
    GSM = 0,
    GSM_COMPACT = 1,
    UTRAN = 2,
    GSM_EDGE = 3,
    UTRAN_HSDPA = 4,
    UTRAN_HSUPA = 5,
    UTRAN_HSDPA_HSUPA = 6,
    LTE = 7,
    LTE_CAT_M1 = 8,
    LTE_NB_IOT = 9
};

typedef enum PlatformNCPManufacturer {
    PLATFORM_NCP_MANUFACTURER_UNKNOWN,
    PLATFORM_NCP_MANUFACTURER_ESPRESSIF = 1,
    PLATFORM_NCP_MANUFACTURER_UBLOX = 2,
    PLATFORM_NCP_MANUFACTURER_QUECTEL = 3,
    PLATFORM_NCP_MANUFACTURER_BROADCOM = 4,
    PLATFORM_NCP_MANUFACTURER_REALTEK = 5
} PlatformNCPManufacturer;

#define PLATFORM_NCP_IDENTIFIER(mf,t) (t|(mf<<5))
#define PLATFORM_NCP_MANUFACTURER(v) ((v) >> 5)

typedef enum PlatformNCPIdentifier {
    PLATFORM_NCP_UNKNOWN = 0xffff,
    PLATFORM_NCP_NONE = 0,

    // 0x4x
    PLATFORM_NCP_SARA_U201 = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_UBLOX, 2),
    PLATFORM_NCP_SARA_G350 = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_UBLOX, 3),
    PLATFORM_NCP_SARA_R410 = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_UBLOX, 4),
    PLATFORM_NCP_SARA_U260 = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_UBLOX, 5),
    PLATFORM_NCP_SARA_U270 = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_UBLOX, 6),
    PLATFORM_NCP_SARA_R510 = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_UBLOX, 7),

    // 0x6x
    PLATFORM_NCP_QUECTEL_BG96      = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 1),
    PLATFORM_NCP_QUECTEL_EG91_E    = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 2),
    PLATFORM_NCP_QUECTEL_EG91_NA   = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 3),
    PLATFORM_NCP_QUECTEL_EG91_EX   = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 4),
    PLATFORM_NCP_QUECTEL_BG95_M1   = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 5),
    PLATFORM_NCP_QUECTEL_EG91_NAX  = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 6),
    PLATFORM_NCP_QUECTEL_BG77      = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 7),
    PLATFORM_NCP_QUECTEL_BG95_MF   = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 8),
    PLATFORM_NCP_QUECTEL_BG95_M6   = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 9),
    PLATFORM_NCP_QUECTEL_BG95_M5   = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 10),
    PLATFORM_NCP_QUECTEL_EG800Q_NA = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 11),
    PLATFORM_NCP_QUECTEL_EG800Q_EU = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 12),
    PLATFORM_NCP_QUECTEL_BG95_S5   = PLATFORM_NCP_IDENTIFIER(PLATFORM_NCP_MANUFACTURER_QUECTEL, 13),

} PlatformNCPIdentifier;
