SYSTEM_MODULE_NAME = system
SYSTEM_MODULE_PATH ?= $(PROJECT_ROOT)/$(SYSTEM_MODULE_NAME)
include $(call rwildcard,$(SYSTEM_MODULE_PATH)/,include.mk)

SYSTEM_BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)
SYSTEM_LIB_DIR = $(BUILD_PATH_BASE)/$(SYSTEM_MODULE_NAME)/$(SYSTEM_BUILD_PATH_EXT)
SYSTEM_LIB_DEP = $(SYSTEM_LIB_DIR)/lib$(SYSTEM_MODULE_NAME).a
