#ifndef TESTERMTPTYPES_H
#define	TESTERMTPTYPES_H

enum EfuseDataTypes {
    EFUSE_DATA_FLASH_ENCRYPTION_KEY,
    EFUSE_DATA_FLASH_ENCRYPTION_LOCK_BITS,
    EFUSE_DATA_SECURE_BOOT_KEY,
    EFUSE_DATA_SECURE_BOOT_LOCK_BITS,
    EFUSE_DATA_WIFI_MAC,
    EFUSE_DATA_MOBILE_SECRET,
    EFUSE_DATA_SERIAL_NUMBER,
    EFUSE_DATA_HARDWARE_VERSION,
    EFUSE_DATA_HARDWARE_MODEL,
    EFUSE_DATA_MAX
};

#endif	/* TESTERMTPTYPES_H */
