#ifndef TESTERCOMMANDTYPES_H
#define	TESTERCOMMANDTYPES_H

enum class TesterCommandType {
    NONE = 0,

    SET_FLASH_ENCRYPTION_KEY,
    ENABLE_FLASH_ENCRYPTION,
    SET_SECURE_BOOT_KEY,
    GET_SECURE_BOOT_KEY,
    ENABLE_SECURE_BOOT,
    TEST_COMMAND,
    READ_SERIAL_NUMBER,
    SET_SERIAL_NUMBER,
    READ_MOBILE_SECRET,
    SET_MOBILE_SECRET,
    READ_HW_DATA,
    SET_HW_DATA,
    READ_HW_MODEL,
    SET_HW_MODEL,
    READ_WIFI_MAC,
    SET_WIFI_MAC,

    END
};

#endif	/* TESTERCOMMANDTYPES_H */
