#ifndef TESTERCOMMANDTYPES_H
#define	TESTERCOMMANDTYPES_H

enum MfgTestKeyType {
    MFG_TEST_FLASH_ENCRYPTION_KEY,
    MFG_TEST_SECURE_BOOT_KEY,
    MFG_TEST_WIFI_MAC,
    MFG_TEST_MOBILE_SECRET,
    MFG_TEST_SERIAL_NUMBER,
    MFG_TEST_HW_VERSION,
    MFG_TEST_HW_MODEL,
    MFG_TEST_END
};

#endif	/* TESTERCOMMANDTYPES_H */
