#!/bin/bash

set -e

usage() {
  echo "$(basename $0) <test name>"
  echo "Tests:"
  echo -e "  - log_config"
  echo -e "  - update_result"
  echo -e "  - electron_modem_pause"
  echo -e "  - usb_always_attach"
  exit 1
}

cd $(dirname "$0")
this_dir=$(pwd)

PATH="$this_dir/tools:$PATH"
source ./init_env

case $1 in
  log_config)
    ;;
  update_result)
    ;;
  electron_modem_pause)
    ;;
  usb_always_attach)
    ;;
  *)
    usage
    ;;
esac

testname="$1"
shift

cucumber features --expand --tags @"${testname}" $*
