
TARGET_SPARK_SERVICES_PATH=$(SERVICES_MODULE_PATH)

INCLUDE_DIRS += $(TARGET_SPARK_SERVICES_PATH)/inc

SERVICES_DEPS = third_party/nanopb
SERVICES_DEPS_INCLUDE_SCRIPTS =$(foreach module,$(SERVICES_DEPS),$(PROJECT_ROOT)/$(module)/import.mk)
include $(SERVICES_DEPS_INCLUDE_SCRIPTS)

ifneq ($(filter services,$(LIBS)),)
SERVICES_LIB_DEP += $(NANOPB_LIB_DEP)
LIBS += $(notdir $(SERVICES_DEPS))
LIB_DIRS += $(NANOPB_LIB_DIR)
endif
