# define any other settings here, e.g. PATH to your toolchain
#PATH := $(PATH):~/gcc-arm-none-eabi/bin/

# path to your c++ source
CPPSRC += applications/tinker/tinker.cpp

# path to your libraries
#CPPSRC += libraries/telnet/telnetd.cpp

# call make by passing in the APP name e.g.:
# make APP=tinker             (build)
# make APP=tinker program-dfu (flash)
