BOOTLOADER_SRC_STM32F2XX_PATH = $(BOOTLOADER_MODULE_PATH)/src/stm32f2xx

CSRC += $(call target_files,$(BOOTLOADER_SRC_STM32F2XX_PATH)/,*.c)
CPPSRC += $(call target_files,$(BOOTLOADER_SRC_STM32F2XX_PATH)/,*.cpp)

LDFLAGS += -T$(BOOTLOADER_SRC_STM32F2XX_PATH)/linker.ld
LINKER_DEPS += $(BOOTLOADER_SRC_STM32F2XX_PATH)/linker.ld

include $(BOOTLOADER_MODULE_PATH)/src/stm32/sources.mk
