/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "cloud/esim.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(particle_cloud_esim_ListProfilesRequest, particle_cloud_esim_ListProfilesRequest, AUTO)


PB_BIND(particle_cloud_esim_ListProfilesResponse, particle_cloud_esim_ListProfilesResponse, AUTO)


PB_BIND(particle_cloud_esim_ListProfilesResponse_Profile, particle_cloud_esim_ListProfilesResponse_Profile, AUTO)


PB_BIND(particle_cloud_esim_InstallProfileRequest, particle_cloud_esim_InstallProfileRequest, AUTO)


PB_BIND(particle_cloud_esim_InstallProfileResponse, particle_cloud_esim_InstallProfileResponse, AUTO)


PB_BIND(particle_cloud_esim_NotifyProfileInstallRequest, particle_cloud_esim_NotifyProfileInstallRequest, AUTO)


PB_BIND(particle_cloud_esim_NotifyProfileInstallResponse, particle_cloud_esim_NotifyProfileInstallResponse, AUTO)


PB_BIND(particle_cloud_esim_DeleteProfileRequest, particle_cloud_esim_DeleteProfileRequest, AUTO)


PB_BIND(particle_cloud_esim_DeleteProfileResponse, particle_cloud_esim_DeleteProfileResponse, AUTO)


PB_BIND(particle_cloud_esim_SetProfileStateRequest, particle_cloud_esim_SetProfileStateRequest, AUTO)


PB_BIND(particle_cloud_esim_SetProfileStateResponse, particle_cloud_esim_SetProfileStateResponse, AUTO)




