/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "cloud/ledger.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(particle_cloud_LedgerRequest, particle_cloud_LedgerRequest, AUTO)


PB_BIND(particle_cloud_LedgerRequest_ListLedgers, particle_cloud_LedgerRequest_ListLedgers, AUTO)


PB_BIND(particle_cloud_LedgerRequest_GetPage, particle_cloud_LedgerRequest_GetPage, AUTO)


PB_BIND(particle_cloud_LedgerRequest_SyncPage, particle_cloud_LedgerRequest_SyncPage, AUTO)


PB_BIND(particle_cloud_LedgerRequest_Subscribe, particle_cloud_LedgerRequest_Subscribe, AUTO)


PB_BIND(particle_cloud_LedgerRequest_Subscribe_LedgerPages, particle_cloud_LedgerRequest_Subscribe_LedgerPages, AUTO)


PB_BIND(particle_cloud_LedgerRequest_Unsubscribe, particle_cloud_LedgerRequest_Unsubscribe, AUTO)


PB_BIND(particle_cloud_LedgerRequest_Unsubscribe_LedgerPages, particle_cloud_LedgerRequest_Unsubscribe_LedgerPages, AUTO)


PB_BIND(particle_cloud_LedgerRequest_NotifyPageChanged, particle_cloud_LedgerRequest_NotifyPageChanged, AUTO)


PB_BIND(particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages, particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages, AUTO)


PB_BIND(particle_cloud_LedgerResponse, particle_cloud_LedgerResponse, AUTO)


PB_BIND(particle_cloud_LedgerResponse_ListLedgers, particle_cloud_LedgerResponse_ListLedgers, AUTO)


PB_BIND(particle_cloud_LedgerResponse_ListLedgers_Ledger, particle_cloud_LedgerResponse_ListLedgers_Ledger, AUTO)


PB_BIND(particle_cloud_LedgerResponse_GetPage, particle_cloud_LedgerResponse_GetPage, AUTO)


PB_BIND(particle_cloud_LedgerResponse_SyncPage, particle_cloud_LedgerResponse_SyncPage, AUTO)


PB_BIND(particle_cloud_LedgerResponse_Subscribe, particle_cloud_LedgerResponse_Subscribe, AUTO)


PB_BIND(particle_cloud_LedgerResponse_Unsubscribe, particle_cloud_LedgerResponse_Unsubscribe, AUTO)


PB_BIND(particle_cloud_LedgerResponse_NotifyPageChanged, particle_cloud_LedgerResponse_NotifyPageChanged, AUTO)






