/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_PARTICLE_CLOUD_CLOUD_LEDGER_PB_H_INCLUDED
#define PB_PARTICLE_CLOUD_CLOUD_LEDGER_PB_H_INCLUDED
#include <pb.h>
#include "common/ledger.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _particle_cloud_LedgerRequest_Type { 
    particle_cloud_LedgerRequest_Type_INVALID_TYPE = 0, 
    particle_cloud_LedgerRequest_Type_LIST_LEDGERS = 1, 
    particle_cloud_LedgerRequest_Type_GET_PAGE = 2, 
    particle_cloud_LedgerRequest_Type_SYNC_PAGE = 3, 
    particle_cloud_LedgerRequest_Type_SUBSCRIBE = 4, 
    particle_cloud_LedgerRequest_Type_UNSUBSCRIBE = 5, 
    particle_cloud_LedgerRequest_Type_NOTIFY_PAGE_CHANGED = 6 
} particle_cloud_LedgerRequest_Type;

typedef enum _particle_cloud_LedgerRequest_SyncPage_Strategy { 
    particle_cloud_LedgerRequest_SyncPage_Strategy_INVALID_STRATEGY = 0, 
    particle_cloud_LedgerRequest_SyncPage_Strategy_PREFER_DEVICE_CHANGES = 1, 
    particle_cloud_LedgerRequest_SyncPage_Strategy_PREFER_SERVER_CHANGES = 2 
} particle_cloud_LedgerRequest_SyncPage_Strategy;

typedef enum _particle_cloud_LedgerResponse_Result { 
    particle_cloud_LedgerResponse_Result_OK = 0, 
    particle_cloud_LedgerResponse_Result_LEDGER_NOT_FOUND = 1 
} particle_cloud_LedgerResponse_Result;

/* Struct definitions */
typedef struct _particle_cloud_LedgerRequest_GetPage { 
    pb_callback_t ledger_name; 
    pb_callback_t page_name; 
} particle_cloud_LedgerRequest_GetPage;

/* *
 Ledger response. */
typedef struct _particle_cloud_LedgerRequest_ListLedgers { 
    char dummy_field;
} particle_cloud_LedgerRequest_ListLedgers;

typedef struct _particle_cloud_LedgerRequest_NotifyPageChanged { 
    pb_callback_t ledger_pages; 
} particle_cloud_LedgerRequest_NotifyPageChanged;

typedef struct _particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages { 
    pb_callback_t ledger_name; 
    pb_callback_t page_names; 
} particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages;

typedef struct _particle_cloud_LedgerRequest_Subscribe { 
    pb_callback_t ledger_pages; 
} particle_cloud_LedgerRequest_Subscribe;

typedef struct _particle_cloud_LedgerRequest_Subscribe_LedgerPages { 
    pb_callback_t ledger_name; 
    pb_callback_t page_names; 
} particle_cloud_LedgerRequest_Subscribe_LedgerPages;

typedef struct _particle_cloud_LedgerRequest_Unsubscribe { 
    pb_callback_t ledger_pages; 
} particle_cloud_LedgerRequest_Unsubscribe;

typedef struct _particle_cloud_LedgerRequest_Unsubscribe_LedgerPages { 
    pb_callback_t ledger_name; 
    pb_callback_t page_names; 
} particle_cloud_LedgerRequest_Unsubscribe_LedgerPages;

typedef struct _particle_cloud_LedgerResponse_GetPage { 
    pb_callback_t data; 
    pb_callback_t checksum; 
} particle_cloud_LedgerResponse_GetPage;

typedef struct _particle_cloud_LedgerResponse_ListLedgers { 
    pb_callback_t ledgers; 
} particle_cloud_LedgerResponse_ListLedgers;

typedef struct _particle_cloud_LedgerResponse_NotifyPageChanged { 
    char dummy_field;
} particle_cloud_LedgerResponse_NotifyPageChanged;

typedef struct _particle_cloud_LedgerResponse_Subscribe { 
    char dummy_field;
} particle_cloud_LedgerResponse_Subscribe;

typedef struct _particle_cloud_LedgerResponse_SyncPage { 
    pb_callback_t data; 
    pb_callback_t checksum; 
} particle_cloud_LedgerResponse_SyncPage;

typedef struct _particle_cloud_LedgerResponse_Unsubscribe { 
    char dummy_field;
} particle_cloud_LedgerResponse_Unsubscribe;

typedef struct _particle_cloud_LedgerRequest_SyncPage { 
    pb_callback_t ledger_name; 
    pb_callback_t page_name; 
    pb_callback_t checksum; 
    bool has_strategy;
    particle_cloud_LedgerRequest_SyncPage_Strategy strategy; 
    pb_callback_t data; 
} particle_cloud_LedgerRequest_SyncPage;

typedef struct _particle_cloud_LedgerResponse { 
    particle_cloud_LedgerResponse_Result result; 
    pb_callback_t error_message; 
    pb_size_t which_response;
    union {
        particle_cloud_LedgerResponse_ListLedgers list_ledgers;
        particle_cloud_LedgerResponse_GetPage get_page;
        particle_cloud_LedgerResponse_SyncPage sync_page;
        particle_cloud_LedgerResponse_Subscribe subscribe;
        particle_cloud_LedgerResponse_Unsubscribe unsubscribe;
        particle_cloud_LedgerResponse_NotifyPageChanged notify_page_changed;
    } response; 
} particle_cloud_LedgerResponse;

typedef struct _particle_cloud_LedgerResponse_ListLedgers_Ledger { 
    pb_callback_t name; 
    particle_ledger_LedgerScope scope; 
} particle_cloud_LedgerResponse_ListLedgers_Ledger;

/* *
 Ledger request. */
typedef struct _particle_cloud_LedgerRequest { 
    bool has_type;
    particle_cloud_LedgerRequest_Type type; /* /< Request type. Must be set if none of the request-specific fields are set. */
    pb_size_t which_request;
    union {
        particle_cloud_LedgerRequest_ListLedgers list_ledgers;
        particle_cloud_LedgerRequest_GetPage get_page;
        particle_cloud_LedgerRequest_SyncPage sync_page;
        particle_cloud_LedgerRequest_Subscribe subscribe;
        particle_cloud_LedgerRequest_Unsubscribe unsubscribe;
        particle_cloud_LedgerRequest_NotifyPageChanged notify_page_changed;
    } request; 
} particle_cloud_LedgerRequest;


/* Helper constants for enums */
#define _particle_cloud_LedgerRequest_Type_MIN particle_cloud_LedgerRequest_Type_INVALID_TYPE
#define _particle_cloud_LedgerRequest_Type_MAX particle_cloud_LedgerRequest_Type_NOTIFY_PAGE_CHANGED
#define _particle_cloud_LedgerRequest_Type_ARRAYSIZE ((particle_cloud_LedgerRequest_Type)(particle_cloud_LedgerRequest_Type_NOTIFY_PAGE_CHANGED+1))

#define _particle_cloud_LedgerRequest_SyncPage_Strategy_MIN particle_cloud_LedgerRequest_SyncPage_Strategy_INVALID_STRATEGY
#define _particle_cloud_LedgerRequest_SyncPage_Strategy_MAX particle_cloud_LedgerRequest_SyncPage_Strategy_PREFER_SERVER_CHANGES
#define _particle_cloud_LedgerRequest_SyncPage_Strategy_ARRAYSIZE ((particle_cloud_LedgerRequest_SyncPage_Strategy)(particle_cloud_LedgerRequest_SyncPage_Strategy_PREFER_SERVER_CHANGES+1))

#define _particle_cloud_LedgerResponse_Result_MIN particle_cloud_LedgerResponse_Result_OK
#define _particle_cloud_LedgerResponse_Result_MAX particle_cloud_LedgerResponse_Result_LEDGER_NOT_FOUND
#define _particle_cloud_LedgerResponse_Result_ARRAYSIZE ((particle_cloud_LedgerResponse_Result)(particle_cloud_LedgerResponse_Result_LEDGER_NOT_FOUND+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define particle_cloud_LedgerRequest_init_default {false, _particle_cloud_LedgerRequest_Type_MIN, 0, {particle_cloud_LedgerRequest_ListLedgers_init_default}}
#define particle_cloud_LedgerRequest_ListLedgers_init_default {0}
#define particle_cloud_LedgerRequest_GetPage_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_LedgerRequest_SyncPage_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, _particle_cloud_LedgerRequest_SyncPage_Strategy_MIN, {{NULL}, NULL}}
#define particle_cloud_LedgerRequest_Subscribe_init_default {{{NULL}, NULL}}
#define particle_cloud_LedgerRequest_Subscribe_LedgerPages_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_LedgerRequest_Unsubscribe_init_default {{{NULL}, NULL}}
#define particle_cloud_LedgerRequest_Unsubscribe_LedgerPages_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_LedgerRequest_NotifyPageChanged_init_default {{{NULL}, NULL}}
#define particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_LedgerResponse_init_default {_particle_cloud_LedgerResponse_Result_MIN, {{NULL}, NULL}, 0, {particle_cloud_LedgerResponse_ListLedgers_init_default}}
#define particle_cloud_LedgerResponse_ListLedgers_init_default {{{NULL}, NULL}}
#define particle_cloud_LedgerResponse_ListLedgers_Ledger_init_default {{{NULL}, NULL}, _particle_ledger_LedgerScope_MIN}
#define particle_cloud_LedgerResponse_GetPage_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_LedgerResponse_SyncPage_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_LedgerResponse_Subscribe_init_default {0}
#define particle_cloud_LedgerResponse_Unsubscribe_init_default {0}
#define particle_cloud_LedgerResponse_NotifyPageChanged_init_default {0}
#define particle_cloud_LedgerRequest_init_zero   {false, _particle_cloud_LedgerRequest_Type_MIN, 0, {particle_cloud_LedgerRequest_ListLedgers_init_zero}}
#define particle_cloud_LedgerRequest_ListLedgers_init_zero {0}
#define particle_cloud_LedgerRequest_GetPage_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_LedgerRequest_SyncPage_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, _particle_cloud_LedgerRequest_SyncPage_Strategy_MIN, {{NULL}, NULL}}
#define particle_cloud_LedgerRequest_Subscribe_init_zero {{{NULL}, NULL}}
#define particle_cloud_LedgerRequest_Subscribe_LedgerPages_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_LedgerRequest_Unsubscribe_init_zero {{{NULL}, NULL}}
#define particle_cloud_LedgerRequest_Unsubscribe_LedgerPages_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_LedgerRequest_NotifyPageChanged_init_zero {{{NULL}, NULL}}
#define particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_LedgerResponse_init_zero  {_particle_cloud_LedgerResponse_Result_MIN, {{NULL}, NULL}, 0, {particle_cloud_LedgerResponse_ListLedgers_init_zero}}
#define particle_cloud_LedgerResponse_ListLedgers_init_zero {{{NULL}, NULL}}
#define particle_cloud_LedgerResponse_ListLedgers_Ledger_init_zero {{{NULL}, NULL}, _particle_ledger_LedgerScope_MIN}
#define particle_cloud_LedgerResponse_GetPage_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_LedgerResponse_SyncPage_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_LedgerResponse_Subscribe_init_zero {0}
#define particle_cloud_LedgerResponse_Unsubscribe_init_zero {0}
#define particle_cloud_LedgerResponse_NotifyPageChanged_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define particle_cloud_LedgerRequest_GetPage_ledger_name_tag 1
#define particle_cloud_LedgerRequest_GetPage_page_name_tag 2
#define particle_cloud_LedgerRequest_NotifyPageChanged_ledger_pages_tag 1
#define particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages_ledger_name_tag 1
#define particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages_page_names_tag 2
#define particle_cloud_LedgerRequest_Subscribe_ledger_pages_tag 1
#define particle_cloud_LedgerRequest_Subscribe_LedgerPages_ledger_name_tag 1
#define particle_cloud_LedgerRequest_Subscribe_LedgerPages_page_names_tag 2
#define particle_cloud_LedgerRequest_Unsubscribe_ledger_pages_tag 1
#define particle_cloud_LedgerRequest_Unsubscribe_LedgerPages_ledger_name_tag 1
#define particle_cloud_LedgerRequest_Unsubscribe_LedgerPages_page_names_tag 2
#define particle_cloud_LedgerResponse_GetPage_data_tag 1
#define particle_cloud_LedgerResponse_GetPage_checksum_tag 2
#define particle_cloud_LedgerResponse_ListLedgers_ledgers_tag 1
#define particle_cloud_LedgerResponse_SyncPage_data_tag 1
#define particle_cloud_LedgerResponse_SyncPage_checksum_tag 2
#define particle_cloud_LedgerRequest_SyncPage_ledger_name_tag 1
#define particle_cloud_LedgerRequest_SyncPage_page_name_tag 2
#define particle_cloud_LedgerRequest_SyncPage_checksum_tag 3
#define particle_cloud_LedgerRequest_SyncPage_strategy_tag 4
#define particle_cloud_LedgerRequest_SyncPage_data_tag 5
#define particle_cloud_LedgerResponse_result_tag 1
#define particle_cloud_LedgerResponse_error_message_tag 2
#define particle_cloud_LedgerResponse_list_ledgers_tag 3
#define particle_cloud_LedgerResponse_get_page_tag 4
#define particle_cloud_LedgerResponse_sync_page_tag 5
#define particle_cloud_LedgerResponse_subscribe_tag 6
#define particle_cloud_LedgerResponse_unsubscribe_tag 7
#define particle_cloud_LedgerResponse_notify_page_changed_tag 8
#define particle_cloud_LedgerResponse_ListLedgers_Ledger_name_tag 1
#define particle_cloud_LedgerResponse_ListLedgers_Ledger_scope_tag 2
#define particle_cloud_LedgerRequest_type_tag    1
#define particle_cloud_LedgerRequest_list_ledgers_tag 2
#define particle_cloud_LedgerRequest_get_page_tag 3
#define particle_cloud_LedgerRequest_sync_page_tag 4
#define particle_cloud_LedgerRequest_subscribe_tag 5
#define particle_cloud_LedgerRequest_unsubscribe_tag 6
#define particle_cloud_LedgerRequest_notify_page_changed_tag 7

/* Struct field encoding specification for nanopb */
#define particle_cloud_LedgerRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,list_ledgers,request.list_ledgers),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,get_page,request.get_page),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sync_page,request.sync_page),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,subscribe,request.subscribe),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,unsubscribe,request.unsubscribe),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,notify_page_changed,request.notify_page_changed),   7)
#define particle_cloud_LedgerRequest_CALLBACK NULL
#define particle_cloud_LedgerRequest_DEFAULT NULL
#define particle_cloud_LedgerRequest_request_list_ledgers_MSGTYPE particle_cloud_LedgerRequest_ListLedgers
#define particle_cloud_LedgerRequest_request_get_page_MSGTYPE particle_cloud_LedgerRequest_GetPage
#define particle_cloud_LedgerRequest_request_sync_page_MSGTYPE particle_cloud_LedgerRequest_SyncPage
#define particle_cloud_LedgerRequest_request_subscribe_MSGTYPE particle_cloud_LedgerRequest_Subscribe
#define particle_cloud_LedgerRequest_request_unsubscribe_MSGTYPE particle_cloud_LedgerRequest_Unsubscribe
#define particle_cloud_LedgerRequest_request_notify_page_changed_MSGTYPE particle_cloud_LedgerRequest_NotifyPageChanged

#define particle_cloud_LedgerRequest_ListLedgers_FIELDLIST(X, a) \

#define particle_cloud_LedgerRequest_ListLedgers_CALLBACK NULL
#define particle_cloud_LedgerRequest_ListLedgers_DEFAULT NULL

#define particle_cloud_LedgerRequest_GetPage_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   ledger_name,       1) \
X(a, CALLBACK, SINGULAR, STRING,   page_name,         2)
#define particle_cloud_LedgerRequest_GetPage_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerRequest_GetPage_DEFAULT NULL

#define particle_cloud_LedgerRequest_SyncPage_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   ledger_name,       1) \
X(a, CALLBACK, SINGULAR, STRING,   page_name,         2) \
X(a, CALLBACK, SINGULAR, BYTES,    checksum,          3) \
X(a, STATIC,   OPTIONAL, UENUM,    strategy,          4) \
X(a, CALLBACK, OPTIONAL, BYTES,    data,              5)
#define particle_cloud_LedgerRequest_SyncPage_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerRequest_SyncPage_DEFAULT NULL

#define particle_cloud_LedgerRequest_Subscribe_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  ledger_pages,      1)
#define particle_cloud_LedgerRequest_Subscribe_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerRequest_Subscribe_DEFAULT NULL
#define particle_cloud_LedgerRequest_Subscribe_ledger_pages_MSGTYPE particle_cloud_LedgerRequest_Subscribe_LedgerPages

#define particle_cloud_LedgerRequest_Subscribe_LedgerPages_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   ledger_name,       1) \
X(a, CALLBACK, REPEATED, STRING,   page_names,        2)
#define particle_cloud_LedgerRequest_Subscribe_LedgerPages_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerRequest_Subscribe_LedgerPages_DEFAULT NULL

#define particle_cloud_LedgerRequest_Unsubscribe_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  ledger_pages,      1)
#define particle_cloud_LedgerRequest_Unsubscribe_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerRequest_Unsubscribe_DEFAULT NULL
#define particle_cloud_LedgerRequest_Unsubscribe_ledger_pages_MSGTYPE particle_cloud_LedgerRequest_Unsubscribe_LedgerPages

#define particle_cloud_LedgerRequest_Unsubscribe_LedgerPages_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   ledger_name,       1) \
X(a, CALLBACK, REPEATED, STRING,   page_names,        2)
#define particle_cloud_LedgerRequest_Unsubscribe_LedgerPages_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerRequest_Unsubscribe_LedgerPages_DEFAULT NULL

#define particle_cloud_LedgerRequest_NotifyPageChanged_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  ledger_pages,      1)
#define particle_cloud_LedgerRequest_NotifyPageChanged_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerRequest_NotifyPageChanged_DEFAULT NULL
#define particle_cloud_LedgerRequest_NotifyPageChanged_ledger_pages_MSGTYPE particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages

#define particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   ledger_name,       1) \
X(a, CALLBACK, REPEATED, STRING,   page_names,        2)
#define particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages_DEFAULT NULL

#define particle_cloud_LedgerResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    result,            1) \
X(a, CALLBACK, OPTIONAL, STRING,   error_message,     2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,list_ledgers,response.list_ledgers),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,get_page,response.get_page),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,sync_page,response.sync_page),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,subscribe,response.subscribe),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,unsubscribe,response.unsubscribe),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,notify_page_changed,response.notify_page_changed),   8)
#define particle_cloud_LedgerResponse_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerResponse_DEFAULT NULL
#define particle_cloud_LedgerResponse_response_list_ledgers_MSGTYPE particle_cloud_LedgerResponse_ListLedgers
#define particle_cloud_LedgerResponse_response_get_page_MSGTYPE particle_cloud_LedgerResponse_GetPage
#define particle_cloud_LedgerResponse_response_sync_page_MSGTYPE particle_cloud_LedgerResponse_SyncPage
#define particle_cloud_LedgerResponse_response_subscribe_MSGTYPE particle_cloud_LedgerResponse_Subscribe
#define particle_cloud_LedgerResponse_response_unsubscribe_MSGTYPE particle_cloud_LedgerResponse_Unsubscribe
#define particle_cloud_LedgerResponse_response_notify_page_changed_MSGTYPE particle_cloud_LedgerResponse_NotifyPageChanged

#define particle_cloud_LedgerResponse_ListLedgers_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  ledgers,           1)
#define particle_cloud_LedgerResponse_ListLedgers_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerResponse_ListLedgers_DEFAULT NULL
#define particle_cloud_LedgerResponse_ListLedgers_ledgers_MSGTYPE particle_cloud_LedgerResponse_ListLedgers_Ledger

#define particle_cloud_LedgerResponse_ListLedgers_Ledger_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UENUM,    scope,             2)
#define particle_cloud_LedgerResponse_ListLedgers_Ledger_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerResponse_ListLedgers_Ledger_DEFAULT NULL

#define particle_cloud_LedgerResponse_GetPage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1) \
X(a, CALLBACK, SINGULAR, BYTES,    checksum,          2)
#define particle_cloud_LedgerResponse_GetPage_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerResponse_GetPage_DEFAULT NULL

#define particle_cloud_LedgerResponse_SyncPage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1) \
X(a, CALLBACK, SINGULAR, BYTES,    checksum,          2)
#define particle_cloud_LedgerResponse_SyncPage_CALLBACK pb_default_field_callback
#define particle_cloud_LedgerResponse_SyncPage_DEFAULT NULL

#define particle_cloud_LedgerResponse_Subscribe_FIELDLIST(X, a) \

#define particle_cloud_LedgerResponse_Subscribe_CALLBACK NULL
#define particle_cloud_LedgerResponse_Subscribe_DEFAULT NULL

#define particle_cloud_LedgerResponse_Unsubscribe_FIELDLIST(X, a) \

#define particle_cloud_LedgerResponse_Unsubscribe_CALLBACK NULL
#define particle_cloud_LedgerResponse_Unsubscribe_DEFAULT NULL

#define particle_cloud_LedgerResponse_NotifyPageChanged_FIELDLIST(X, a) \

#define particle_cloud_LedgerResponse_NotifyPageChanged_CALLBACK NULL
#define particle_cloud_LedgerResponse_NotifyPageChanged_DEFAULT NULL

extern const pb_msgdesc_t particle_cloud_LedgerRequest_msg;
extern const pb_msgdesc_t particle_cloud_LedgerRequest_ListLedgers_msg;
extern const pb_msgdesc_t particle_cloud_LedgerRequest_GetPage_msg;
extern const pb_msgdesc_t particle_cloud_LedgerRequest_SyncPage_msg;
extern const pb_msgdesc_t particle_cloud_LedgerRequest_Subscribe_msg;
extern const pb_msgdesc_t particle_cloud_LedgerRequest_Subscribe_LedgerPages_msg;
extern const pb_msgdesc_t particle_cloud_LedgerRequest_Unsubscribe_msg;
extern const pb_msgdesc_t particle_cloud_LedgerRequest_Unsubscribe_LedgerPages_msg;
extern const pb_msgdesc_t particle_cloud_LedgerRequest_NotifyPageChanged_msg;
extern const pb_msgdesc_t particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages_msg;
extern const pb_msgdesc_t particle_cloud_LedgerResponse_msg;
extern const pb_msgdesc_t particle_cloud_LedgerResponse_ListLedgers_msg;
extern const pb_msgdesc_t particle_cloud_LedgerResponse_ListLedgers_Ledger_msg;
extern const pb_msgdesc_t particle_cloud_LedgerResponse_GetPage_msg;
extern const pb_msgdesc_t particle_cloud_LedgerResponse_SyncPage_msg;
extern const pb_msgdesc_t particle_cloud_LedgerResponse_Subscribe_msg;
extern const pb_msgdesc_t particle_cloud_LedgerResponse_Unsubscribe_msg;
extern const pb_msgdesc_t particle_cloud_LedgerResponse_NotifyPageChanged_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define particle_cloud_LedgerRequest_fields &particle_cloud_LedgerRequest_msg
#define particle_cloud_LedgerRequest_ListLedgers_fields &particle_cloud_LedgerRequest_ListLedgers_msg
#define particle_cloud_LedgerRequest_GetPage_fields &particle_cloud_LedgerRequest_GetPage_msg
#define particle_cloud_LedgerRequest_SyncPage_fields &particle_cloud_LedgerRequest_SyncPage_msg
#define particle_cloud_LedgerRequest_Subscribe_fields &particle_cloud_LedgerRequest_Subscribe_msg
#define particle_cloud_LedgerRequest_Subscribe_LedgerPages_fields &particle_cloud_LedgerRequest_Subscribe_LedgerPages_msg
#define particle_cloud_LedgerRequest_Unsubscribe_fields &particle_cloud_LedgerRequest_Unsubscribe_msg
#define particle_cloud_LedgerRequest_Unsubscribe_LedgerPages_fields &particle_cloud_LedgerRequest_Unsubscribe_LedgerPages_msg
#define particle_cloud_LedgerRequest_NotifyPageChanged_fields &particle_cloud_LedgerRequest_NotifyPageChanged_msg
#define particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages_fields &particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages_msg
#define particle_cloud_LedgerResponse_fields &particle_cloud_LedgerResponse_msg
#define particle_cloud_LedgerResponse_ListLedgers_fields &particle_cloud_LedgerResponse_ListLedgers_msg
#define particle_cloud_LedgerResponse_ListLedgers_Ledger_fields &particle_cloud_LedgerResponse_ListLedgers_Ledger_msg
#define particle_cloud_LedgerResponse_GetPage_fields &particle_cloud_LedgerResponse_GetPage_msg
#define particle_cloud_LedgerResponse_SyncPage_fields &particle_cloud_LedgerResponse_SyncPage_msg
#define particle_cloud_LedgerResponse_Subscribe_fields &particle_cloud_LedgerResponse_Subscribe_msg
#define particle_cloud_LedgerResponse_Unsubscribe_fields &particle_cloud_LedgerResponse_Unsubscribe_msg
#define particle_cloud_LedgerResponse_NotifyPageChanged_fields &particle_cloud_LedgerResponse_NotifyPageChanged_msg

/* Maximum encoded size of messages (where known) */
/* particle_cloud_LedgerRequest_size depends on runtime parameters */
/* particle_cloud_LedgerRequest_GetPage_size depends on runtime parameters */
/* particle_cloud_LedgerRequest_SyncPage_size depends on runtime parameters */
/* particle_cloud_LedgerRequest_Subscribe_size depends on runtime parameters */
/* particle_cloud_LedgerRequest_Subscribe_LedgerPages_size depends on runtime parameters */
/* particle_cloud_LedgerRequest_Unsubscribe_size depends on runtime parameters */
/* particle_cloud_LedgerRequest_Unsubscribe_LedgerPages_size depends on runtime parameters */
/* particle_cloud_LedgerRequest_NotifyPageChanged_size depends on runtime parameters */
/* particle_cloud_LedgerRequest_NotifyPageChanged_LedgerPages_size depends on runtime parameters */
/* particle_cloud_LedgerResponse_size depends on runtime parameters */
/* particle_cloud_LedgerResponse_ListLedgers_size depends on runtime parameters */
/* particle_cloud_LedgerResponse_ListLedgers_Ledger_size depends on runtime parameters */
/* particle_cloud_LedgerResponse_GetPage_size depends on runtime parameters */
/* particle_cloud_LedgerResponse_SyncPage_size depends on runtime parameters */
#define particle_cloud_LedgerRequest_ListLedgers_size 0
#define particle_cloud_LedgerResponse_NotifyPageChanged_size 0
#define particle_cloud_LedgerResponse_Subscribe_size 0
#define particle_cloud_LedgerResponse_Unsubscribe_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
