INCLUDE_DIRS += $(BOOST_ROOT)
INCLUDE_DIRS += $(PROJECT_ROOT)/proto_defs/src
INCLUDE_DIRS += $(MODULE_PATH)/$(USRSRC)/mqtt_cpp/include

CPPFLAGS += -DMQTT_USE_TLS -DMQTT_STD_STRING_VIEW -DMQTT_STD_OPTIONAL
