TARGET_CRYPTO_PATH = $(CRYPTO_MODULE_PATH)
INCLUDE_DIRS += $(TARGET_CRYPTO_PATH)/inc

CRYPTO_DEPS = third_party/mbedtls
CRYPTO_DEPS_INCLUDE_SCRIPTS =$(foreach module,$(CRYPTO_DEPS),$(PROJECT_ROOT)/$(module)/import.mk)
include $(CRYPTO_DEPS_INCLUDE_SCRIPTS)

CRYPTO_LIB_DEP += $(MBEDTLS_LIB_DEP)
LIBS += $(notdir $(CRYPTO_DEPS))
LIB_DIRS += $(MBEDTLS_LIB_DIR)
