TARGET_CRYPTO_DYNALIB_SRC_PATH = $(CRYPTO_DYNALIB_MODULE_PATH)/src

CPPSRC += $(call target_files,$(TARGET_CRYPTO_DYNALIB_SRC_PATH),*.cpp)
CSRC += $(call target_files,$(TARGET_CRYPTO_DYNALIB_SRC_PATH),*.c)
