MODULE=gsm0710muxer
GSM0710MUXER_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a

BUILD_PATH_EXT=$(GSM0710MUXER_BUILD_PATH_EXT)

DEPENDENCIES = hal services platform

# PROJECT_ROOT ?= ../..
include ../build/arm-tlm.mk
