
#include "testapi.h"

test(usart_hal_backwards_compatibility)
{
    // These APIs are exposed to user application.
    API_COMPILE(HAL_USART_Init(HAL_USART_SERIAL1, NULL, NULL));
    API_COMPILE(HAL_USART_Begin(HAL_USART_SERIAL1, 0));
    API_COMPILE(HAL_USART_End(HAL_USART_SERIAL1));
    API_COMPILE(HAL_USART_Write_Data(HAL_USART_SERIAL1, 0));
    API_COMPILE(HAL_USART_Available_Data_For_Write(HAL_USART_SERIAL1));
    API_COMPILE(HAL_USART_Available_Data(HAL_USART_SERIAL1));
    API_COMPILE(HAL_USART_Read_Data(HAL_USART_SERIAL1));
    API_COMPILE(HAL_USART_Peek_Data(HAL_USART_SERIAL1));
    API_COMPILE(HAL_USART_Flush_Data(HAL_USART_SERIAL1));
    API_COMPILE(HAL_USART_Is_Enabled(HAL_USART_SERIAL1));
    API_COMPILE(HAL_USART_Half_Duplex(HAL_USART_SERIAL1, 0));
    API_COMPILE(HAL_USART_BeginConfig(HAL_USART_SERIAL1, 0, 0, NULL));
    API_COMPILE(HAL_USART_Write_NineBitData(HAL_USART_SERIAL1, 0));
    API_COMPILE(HAL_USART_Send_Break(HAL_USART_SERIAL1, NULL));
    API_COMPILE(HAL_USART_Break_Detected(HAL_USART_SERIAL1));
}
