TARGET_SERVICES_DYNALIB_SRC_PATH = $(SERVICES_DYNALIB_MODULE_PATH)/src

CPPSRC += $(call target_files,$(TARGET_SERVICES_DYNALIB_SRC_PATH),*.cpp)
CSRC += $(call target_files,$(TARGET_SERVICES_DYNALIB_SRC_PATH),*.c)

