/**
 * The dyanmic libraries exported by this module.
 */
PROVIDE ( dynalib_location_system_module_part3 = _system_part3_dynalib_table_flash_start + 0 );
PROVIDE ( dynalib_location_hal_usb = _system_part3_dynalib_table_flash_start + 4 );
PROVIDE ( dynalib_location_hal_cellular = _system_part3_dynalib_table_flash_start + 8 );
PROVIDE ( dynalib_location_hal_socket = _system_part3_dynalib_table_flash_start + 12 );
PROVIDE ( dynalib_location_hal_bootloader = _system_part3_dynalib_table_flash_start + 16 );
PROVIDE ( dynalib_location_services2 = _system_part3_dynalib_table_flash_start + 20 );
