MODULE=bootloader
PLATFORM_NET=CC3000
PLATFORM_MCU=STM32

# Target this makefile is building.
TARGET=elf bin hex size lst

DEPENDENCIES = platform hal services
MAKE_DEPENDENCIES = platform services

include ../build/arm-tlm.mk
