
MODULE=wiring_globals
WIRING_GLOBALS_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)

# the only true dependency is Wiring, the others are transitive dependencies
DEPENDENCIES = wiring hal services system platform communication

include ../build/arm-tlm.mk
