CRYPTO_MODULE_NAME = crypto
CRYPTO_MODULE_PATH ?= $(PROJECT_ROOT)/$(CRYPTO_MODULE_NAME)
include $(call rwildcard,$(CRYPTO_MODULE_PATH)/,include.mk)

CRYPTO_BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)
CRYPTO_LIB_DIR = $(BUILD_PATH_BASE)/$(CRYPTO_MODULE_NAME)/$(CRYPTO_BUILD_PATH_EXT)
CRYPTO_LIB_DEP = $(CRYPTO_LIB_DIR)/lib$(CRYPTO_MODULE_NAME).a

CFLAGS += -DMBEDTLS_CONFIG_FILE="<mbedtls_config.h>"
