
MODULE=crypto
CRYPTO_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a

BUILD_PATH_EXT=$(CRYPTO_BUILD_PATH_EXT)

DEPENDENCIES = dynalib hal platform third_party/mbedtls
MAKE_DEPENDENCIES = third_party/mbedtls

include ../build/arm-tlm.mk
