
MODULE=newlib_nano
NEWLIBNANO_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT = $(NEWLIBNANO_BUILD_PATH_EXT)

DEPENDENCIES = hal services platform

include ../build/arm-tlm.mk
