PREBOOTLOADER_PART1_SRC_PATH = $(PREBOOTLOADER_PART1_MODULE_PATH)

CSRC += $(call target_files,$(PREBOOTLOADER_PART1_SRC_PATH)/,*.c)
CPPSRC += $(call target_files,$(PREBOOTLOADER_PART1_SRC_PATH)/,*.cpp)

LDFLAGS += -T$(PREBOOTLOADER_PART1_SRC_PATH)/linker.ld
LINKER_DEPS += $(PREBOOTLOADER_PART1_SRC_PATH)/linker.ld
