/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_PARTICLE_FIRMWARE_LEDGER_PB_H_INCLUDED
#define PB_PARTICLE_FIRMWARE_LEDGER_PB_H_INCLUDED
#include <pb.h>
#include "common/ledger.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* *
 Ledger info. */
typedef struct _particle_firmware_LedgerInfo { 
    pb_callback_t name; /* /< Ledger name. Not set for a device ledger. */
    particle_ledger_LedgerScope scope; /* /< Ledger scope. */
} particle_firmware_LedgerInfo;

/* *
 Page info. */
typedef struct _particle_firmware_LedgerPageInfo { 
    pb_callback_t name; /* /< Page name. */
    bool has_updated_at;
    uint64_t updated_at; /* /< Last time the page was updated, in milliseconds since the Unix epoch. */
    bool deleted; /* /< Whether the page was deleted locally. */
} particle_firmware_LedgerPageInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define particle_firmware_LedgerPageInfo_init_default {{{NULL}, NULL}, false, 0, 0}
#define particle_firmware_LedgerInfo_init_default {{{NULL}, NULL}, _particle_ledger_LedgerScope_MIN}
#define particle_firmware_LedgerPageInfo_init_zero {{{NULL}, NULL}, false, 0, 0}
#define particle_firmware_LedgerInfo_init_zero   {{{NULL}, NULL}, _particle_ledger_LedgerScope_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define particle_firmware_LedgerInfo_name_tag    1
#define particle_firmware_LedgerInfo_scope_tag   2
#define particle_firmware_LedgerPageInfo_name_tag 1
#define particle_firmware_LedgerPageInfo_updated_at_tag 2
#define particle_firmware_LedgerPageInfo_deleted_tag 3

/* Struct field encoding specification for nanopb */
#define particle_firmware_LedgerPageInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, FIXED64,  updated_at,        2) \
X(a, STATIC,   SINGULAR, BOOL,     deleted,           3)
#define particle_firmware_LedgerPageInfo_CALLBACK pb_default_field_callback
#define particle_firmware_LedgerPageInfo_DEFAULT NULL

#define particle_firmware_LedgerInfo_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UENUM,    scope,             2)
#define particle_firmware_LedgerInfo_CALLBACK pb_default_field_callback
#define particle_firmware_LedgerInfo_DEFAULT NULL

extern const pb_msgdesc_t particle_firmware_LedgerPageInfo_msg;
extern const pb_msgdesc_t particle_firmware_LedgerInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define particle_firmware_LedgerPageInfo_fields &particle_firmware_LedgerPageInfo_msg
#define particle_firmware_LedgerInfo_fields &particle_firmware_LedgerInfo_msg

/* Maximum encoded size of messages (where known) */
/* particle_firmware_LedgerPageInfo_size depends on runtime parameters */
/* particle_firmware_LedgerInfo_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
