/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "network_config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(particle_firmware_WifiConfig, particle_firmware_WifiConfig, AUTO)


PB_BIND(particle_firmware_WifiConfig_Network, particle_firmware_WifiConfig_Network, AUTO)


PB_BIND(particle_firmware_CellularConfig, particle_firmware_CellularConfig, AUTO)


PB_BIND(particle_firmware_NetworkConfig, particle_firmware_NetworkConfig, AUTO)



