COMMUNICATION_DYNALIB_MODULE_NAME = communication-dynalib
COMMUNICATION_DYNALIB_MODULE_PATH ?= $(PROJECT_ROOT)/$(COMMUNICATION_DYNALIB_MODULE_NAME)
include $(call rwildcard,$(COMMUNICATION_DYNALIB_MODULE_PATH)/,include.mk)

COMMUNICATION_DYNALIB_BUILD_PATH_EXT=$(BUILD_TARGET_PLATFORM)
COMMUNICATION_DYNALIB_LIB_DIR = $(BUILD_PATH_BASE)/$(COMMUNICATION_DYNALIB_MODULE_NAME)/$(COMMUNICATION_DYNALIB_BUILD_PATH_EXT)
COMMUNICATION_DYNALIB_LIB_DEP = $(COMMUNICATION_DYNALIB_LIB_DIR)/lib$(COMMUNICATION_DYNALIB_MODULE_NAME).a

