
MODULE=communication-dynalib
COMMUNICATION_DYNALIB_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT=$(COMMUNICATION_DYNALIB_BUILD_PATH_EXT)

DEPENDENCIES = communication dynalib hal

include ../build/arm-tlm.mk
