
MODULE=communication-dynalib
COMMUNICATION_DYNALIB_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT=$(ARCH)

DEPENDENCIES = communication services

include ../build/arm-tlm.mk
