COMMUNICATION_MODULE_NAME = communication
COMMUNICATION_MODULE_PATH ?= $(PROJECT_ROOT)/$(COMMUNICATION_MODULE_NAME)

ifdef PRODUCT_ID
COMMUNICATION_BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)-prod-$(PRODUCT_ID)
else
COMMUNICATION_BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)
endif

COMMUNICATION_LIB_DIR = $(BUILD_PATH_BASE)/$(COMMUNICATION_MODULE_NAME)/$(COMMUNICATION_BUILD_PATH_EXT)
COMMUNICATION_LIB_DEP = $(COMMUNICATION_LIB_DIR)/lib$(COMMUNICATION_MODULE_NAME).a

PRODUCT_ID ?= 65535
PRODUCT_FIRMWARE_VERSION ?= 65535

CFLAGS += -DPRODUCT_ID=$(PRODUCT_ID)
CFLAGS += -DPRODUCT_FIRMWARE_VERSION=$(PRODUCT_FIRMWARE_VERSION)

include $(call rwildcard,$(COMMUNICATION_MODULE_PATH)/,include.mk)
