COMMUNICATION_MODULE_PATH ?= ../communication
include $(call rwildcard,$(COMMUNICATION_MODULE_PATH)/,include.mk)

COMMUNICATION_LIB_DIR = $(BUILD_PATH_BASE)/communication/$(ARCH)
COMMUNICATION_LIB_DEP = $(COMMUNICATION_LIB_DIR)/libcommunication.a

CFLAGS += -DSPARK_PRODUCT_ID=$(SPARK_PRODUCT_ID)
CFLAGS += -DPRODUCT_FIRMWARE_VERSION=$(PRODUCT_FIRMWARE_VERSION)

SPARK_PRODUCT_ID ?= 65535
PRODUCT_FIRMWARE_VERSION ?= 65535

