
MODULE=communication
COMMUNICATION_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT=$(ARCH)

# for systick_t
DEPENDENCIES = hal services

include ../build/arm-tlm.mk
