
MODULE=communication
COMMUNICATION_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT=prod-$(SPARK_PRODUCT_ID)

# for systick_t
DEPENDENCIES = hal services

include ../build/arm-tlm.mk
